# Downgraded due to lack of support for 3.1.0
openapi: 3.0.3
info:
  title: "Jenkins"
  version: "2.378"
paths:
  /job/{jobName}/buildWithParameters:
    post:
      security:
        - basic: []
      parameters:
        - name: jobName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          multipart/form-data: # Media type
            schema:            # Request payload
              type: object
              properties:      # Request parts
                "INPUT":            # Part 1 (string value)
                  type: string
                  format: binary
      responses:
        '201':
          description: CREATED
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
