apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarqube-namespace

commonLabels:
  ventheAppIdentifier: sonarqube

secretGenerator:
  - name: sonarqube-secret
    type: Opaque
    env: secrets/database-secret.txt

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: sonarqube-service
  path: sonarqube-service-patch.yaml

images:
  - name: postgres
    newTag: "13"
  - name: sonarqube
    newTag: 8.4.2-developer

resources:
  - manifests/namespace.yaml
  - manifests/database.yaml
  - manifests/sonarqube.yaml
