apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  ventheAppIdentifier: kube-system

namespace: kube-system

resources:
  - manifests/grafanak8s-kubestate-deploy.yml
  - manifests/grafanak8s-node-exporter-ds.yml
