---

- name: Install mDNS
  gather_facts: false
  hosts: all
  vars:
    deploy_manifest: true
  tasks:
    - name: Install Avahi
      become: true
      apt:
        name: "avahi-daemon"
        update_cache: yes
    # Run this on main only?
    - name: 'Install External DNS: mDND manifest'
      when: deploy_manifest == true
      command: kubectl apply -f https://raw.githubusercontent.com/tsaarni/k8s-external-mdns/master/external-dns-with-avahi-mdns.yaml
