# config file version
apiVersion: 1
# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Graphite
    orgId: 1
# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: kubernetes-master-node
    type: grafana-kubernetes-app
    access: proxy
    url: https://192.168.3.1:6443
    basicAuth: false
    isDefault: false
    readOnly: false
    jsonData:
      ds: Prometheus
      tlsAuth: true
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCACert: |-
        -----BEGIN CERTIFICATE-----
        MIIC5zCCAc+gAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
        cm5ldGVzMB4XDTIwMDkyMjIyMTUxMVoXDTMwMDkyMDIyMTUxMVowFTETMBEGA1UE
        AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOLW
        KUpnpQW8hQAysKZvx1AtqRDCqvun7r4aDodaWcKzCryHBd5aodkjPmVLMYJPW/SB
        VuMea67gVjhpsmmh9tTGiYOsOZglmyN+PawJWlbarMU8LYjlNP+rk74t2dO81/WF
        XAAHkwe4DrhTxltnuF6L+LUpfffIxerBcyqJxEyJDc9z58s8sBgrea8EvjC7pY93
        ghfwItTz8USW/56xg280K2MAZTngdOug6/1ubU+OVL0DyRi8v30XLehi2WpoDfg0
        VF1EcfT27VVuhd9T9KaEU8yIN9M+zgOP0fPelLrQQeVMEAVmdWoGga4dS7JPjTI1
        7Dl5cTM/W3KiQV0I9xkCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
        /wQFMAMBAf8wHQYDVR0OBBYEFCgMmo+tUlRrCuj5PU77M3gpzZH7MA0GCSqGSIb3
        DQEBCwUAA4IBAQCLt18g2g62DhrEDnF5Pu3BxmQpRql/0KDkhbkUcWoeWiZoi2xU
        n3ez0ftYdXMTtY/uC1Eo/EpOEWOf4FlpA4F8ZHrkoDnuYGAflfRfTW+oX003jwHK
        m1Gz+cht3vIWrDAgPbU8oikLkUUyAXpK1Ofq9sMnIm6YL/SBypLC1G+YH0ByLuiw
        i4+pwg5kuzjeYFmXJEgdWhIx2jWc4dv0Ecy10hnsjZo6/pCRVXSB48Q1HHILBmef
        ULuVinK2Zj+3/zMroKK2nM2IHrCIi+8rSIEBv7Rr17QJI8X9Ee9P4CoarQnHCWRZ
        JoaWKG/d8OjueyCm4dht1kgrmVfNKNCOOwuR
        -----END CERTIFICATE-----
      tlsClientCert: |-
        -----BEGIN CERTIFICATE-----
        MIIDEzCCAfugAwIBAgIIcEnH/ihFIIkwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
        AxMKa3ViZXJuZXRlczAeFw0yMDA5MjIyMjE1MTFaFw0yMTA5MjIyMjE1MTJaMDQx
        FzAVBgNVBAoTDnN5c3RlbTptYXN0ZXJzMRkwFwYDVQQDExBrdWJlcm5ldGVzLWFk
        bWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9/e6vUA/TKvByZef
        MIaMepG/7qfr7F6wTwNHLZlRBKDPri9b5ay+HlB1DC2EimiWF6GG9X1TnlD2LeVq
        hJ+mpfxasM+lcn+kulMXHMAMRtaDkImi5P23extnkBKc9fzlTc6p1iK4J5wTeYzx
        B0/vR/jSnSrNcZgRkl0u/jv2dl9TbLWWh31sZca5hqB1wZxbcX1UaBE2AnauZa7J
        7j97l3m6uTLG7faDyH3NEi+msH03bZnUx0jHnVSxCM/JToIggu7hVw/B6KtsHDZd
        +7qOz6VlNmaItkQSekI+8dPgTpWaHSfBx/vS3qehlAxETHBrvmycan5iBUKMLzQ5
        8JW//wIDAQABo0gwRjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUH
        AwIwHwYDVR0jBBgwFoAUKAyaj61SVGsK6Pk9TvszeCnNkfswDQYJKoZIhvcNAQEL
        BQADggEBANidqyWWZvVtfs4Bs8hbHOyig6mWmHJavGHAYvsh8Wy6eAJcLQGULIMO
        UDivCASs2BOn8O1ZUDEDB220h0uU71ssvokwC9ntjiZQ5u2tDjBx2YUr5YsLhD5F
        C6RTEkzFV2QTmz0TcyVD8lrwoFLrpvYKADBo4Y0o4jbRG08ekn9k38uLIUHsuaYB
        b3OeitCUdFROv3CL+UI2WgAxBXr3s4UvMmg2gkRD/cfdOwBxpe+KX24LvMaOkEYW
        r4zP+0HDKqTQqg9zSMzJswOTzN14FhrPHYADMaxeWiwtYU7r9jUWsv48IyHjwS1g
        nuvHP5W/UN7+azHAZyu4z0S3+JjF5/A=
        -----END CERTIFICATE-----
      tlsClientKey: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEogIBAAKCAQEA9/e6vUA/TKvByZefMIaMepG/7qfr7F6wTwNHLZlRBKDPri9b
        5ay+HlB1DC2EimiWF6GG9X1TnlD2LeVqhJ+mpfxasM+lcn+kulMXHMAMRtaDkImi
        5P23extnkBKc9fzlTc6p1iK4J5wTeYzxB0/vR/jSnSrNcZgRkl0u/jv2dl9TbLWW
        h31sZca5hqB1wZxbcX1UaBE2AnauZa7J7j97l3m6uTLG7faDyH3NEi+msH03bZnU
        x0jHnVSxCM/JToIggu7hVw/B6KtsHDZd+7qOz6VlNmaItkQSekI+8dPgTpWaHSfB
        x/vS3qehlAxETHBrvmycan5iBUKMLzQ58JW//wIDAQABAoIBACLikz70vvMGZuj5
        j8e/5huITbxBm4tRdvRmvajInQFNrmoO95rERqr1HsJr1O2z8Qm6C8aVryHiuf+S
        +v1ViJhpfEjLrbcCBibAccv1qMR+gVvgQS5+E0YagONf+v0QayIbJQGfONE5v/Ol
        xHMG5970Po0l7GlCv5YbzfSucuoMEEfHjjfVzafQKY+V0xlzD3w5bYiEjVy8E2dt
        4ljIuCEV0uL+HbESbnm8SxEkSTHBAjkNsNaclut51OVSN26sV16exPItf/hc+863
        i1+PBb6EA2hBjYd4BQKvXuNVavBb9777ht2TYXHwsbUXG8jbSJ1AM6mAHgdwOsUX
        rUIUdUECgYEA/YCxG3cXmxxNXsXN7MIK8ueeKvXLXcOLs0lLK1cYQfAoPjRYU5+z
        9i94oCZXM0o6OBJTZGtbnKywmUpBDqk7R+RLv/T7iKiyY9qPlPEsVI48Ldh1bRHr
        pft48L9gErbWCdlvxy/dVSpIrccdlv5FcN7NeHFMQWPK/62WG3YW9DcCgYEA+mkU
        MjlEreyTMaq86hZjEbUMwoxQkMvtiBA/XRmtlgIAoiWIk/sSB/wC7pM8O0GMvnBE
        uG42UM+F/ACNtWakv6jLri9BXdlS/QwjHiPsJo3+4CzTSyYGHOYs4pz0BIUCTzX3
        kQ3IjjddoR7DVpDxTCgfgP8zB26Jlz4icNahPnkCgYBM/4PL9dZjtKsDeE1d9mpg
        8V0na1UD+9s477A3T9L8ZDe0/S0+6Sk+Q5j9++dMmuUoFtjhjYJcCk/xn443J8vr
        wDoJ6h1kmujkT4SBFugCHtnEixTPtju/RKytY1OJG6PThgnflHhD3/4HWo1wSXdK
        G0KJrNAepHMKSe1oFexO7QKBgHiC4YlaLkdVt3ELrmcp5vu6mi12wb8tpV76EsSH
        exbaV9uxHI27Iu5cxjxy92W9IjL0bN4ljFZPyTeCPLC0eU0TuxJVA6xazqmhkbUL
        rLbRV3wjlnxwDDkUPT3CM12JdZcRbdeNPpvS4WiNGY0rrDTuilrWdoR5GhaDfKe5
        Y1hhAoGAT0dSlW4YQ2827/cUg8REwE4P+8WDlO1gBvEuknaTmh2nF2OtJTXRovek
        MRjheYlD9LOi97MWVb39Tx9et6LSop5TfF3HkizBIwat6nlxgX5MovIvLq7PbfLv
        CJgsIS6zjEjx/T6pIq1REQ1IbD+vmWCj6B6W0fa7zOR2Q/WkdwM=
        -----END RSA PRIVATE KEY-----
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service:80
    basicAuth: false
    isDefault: true
    readOnly: false
    jsonData: {}
