version: "3.7"

services:

  # https://hub.docker.com/r/jenkins/jenkins/
  jenkins:
    container_name: "jenkins"
    image: jenkins/jenkins:2.190.2-jdk11
    restart: always
    # volumes:
    #   - jenkins-home-volume:/var/jenkins_home
    hostname: "jenkins"
    expose:
      - "50000"
    ports:
      - "11500:50000"
      - "11080:8080"

  # https://hub.docker.com/r/jenkins/slave/
  # jenkins-slave:
  #   image: jenkins/slave:3.35-3-jdk11

  # https://hub.docker.com/r/jenkins/jnlp-slave/
  # jenkins-jnlp-slave:
  #   image: jenkins/jnlp-slave:3.35-5-jdk11
    # environment:
      # url for the Jenkins server, can be used as a replacement to -url option, or to set alternate jenkins URL
      # - JENKINS_URL=jenkins
      # (HOST:PORT) connect to this agent host and port instead of Jenkins server, assuming this one do route TCP traffic to Jenkins master. Useful when when Jenkins runs behind a load balancer, reverse proxy, etc.
      # - JENKINS_TUNNEL
      # agent secret, if not set as an argument
      # - JENKINS_SECRET
      # agent name, if not set as an argument
      # - JENKINS_AGENT_NAME
      # agent work directory, if not set by optional parameter -workDir
      # - JENKINS_AGENT_WORKDIR

  # https://hub.docker.com/_/sonarqube/
  sonarqube:
    container_name: "sonarqube"
    hostname: "sonarqube"
    restart: always
    image: sonarqube:8.0-community-beta
    ports:
      - "9003:9000"
    # volumes:
    #   # configuration files, such as sonar.properties
    #   - sonarqube-conf-volume:/opt/sonarqube/conf
    #   # data files, such as the embedded H2 database and Elasticsearch indexes
    #   - sonarqube-data-volume:/opt/sonarqube/data
    #   # contains SonarQube logs about access, web process, CE process, Elasticsearch logs
    #   - sonarqube-logs-volume:/opt/sonarqube/logs
    #   # plugins, such as language analyzers
    #   - sonarqube-extensions-volume:/opt/sonarqube/extensions


# volumes:
#   jenkins-home-volume:
#   sonarqube-conf-volume:
#   sonarqube-conf-data:
#   sonarqube-conf-logs:
#   sonarqube-conf-extensions:

networks:
  default:
    name: ci-cd
  external:
    name: internal