version: '3.7'

services:

  # https://hub.docker.com/_/postgres
  postgresql:
    container_name: "postgresql"
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
  
  # https://hub.docker.com/r/dpage/pgadmin4
  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4:4.14
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret