- name: Add repository
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.repo_url }}"
  with_items:
    - name: cowboysysop
      repo_url: https://cowboysysop.github.io/charts/
    - name: bitnami
      repo_url: https://charts.bitnami.com/bitnami
- name: Deploy mongodb chart
  kubernetes.core.helm:
    chart_version: "13.6.7"
    create_namespace: true
    update_repo_cache: true
    name: mongodb
    chart_ref: bitnami/mongodb
    release_namespace: "{{ infrastructure.namespace }}"
    values: "{{ lookup('template', './values/mongodb-values.yml') | from_yaml }}"
- name: Deploy mongo-express chart
  kubernetes.core.helm:
    chart_version: "2.8.5"
    create_namespace: true
    update_repo_cache: true
    name: mongo-express
    chart_ref: cowboysysop/mongo-express
    release_namespace: "{{ infrastructure.namespace }}"
    values: "{{ lookup('template', './values/mongo-express-values.yml') | from_yaml }}"
