kind: Service
apiVersion: v1
metadata:
  name: nexus-service
  labels:
    app: nexus
spec:
  type: LoadBalancer
  selector:
    app: nexus
    component: nexus
  ports:
    - port: 80
      targetPort: 8081
      name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus-statefulset
  labels:
    app: nexus
spec:
  serviceName: nexus-service
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
        component: nexus
    spec:
      volumes:
        - name: nexus-secrets
          secret:
            secretName: nexus-secret
      containers:
        # https://hub.docker.com/r/sonatype/nexus3
        - name: nexus-container
          ports:
            - containerPort: 8081
          image: sonatype/nexus3:3.27.0
          volumeMounts:
            - name: nexus-data-persisstentvolumeclaim
              mountPath: /nexus-data
            - name: nexus-secrets
              subPath: security.xml
              mountPath: /sonatype-work/conf/security.xml
  volumeClaimTemplates:
    - metadata:
        name: nexus-data-persisstentvolumeclaim
        labels:
          app: nexus
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
