- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temporary
  register: temporary
- name: Download calico manifest to the cluster.
  ansible.builtin.get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: "{{ temporary.path }}/calico.yaml"
    mode: '0664'
# Fixme: Run this only when necessary
- name: Install calico pod network
  kubernetes.core.k8s:
    state: present
    src: "{{ temporary.path }}/calico.yaml"
- name: Use the registered var and the file module to remove the temporary file
  ansible.builtin.file:
    path: "{{ temporary.path }}"
    state: absent
  when: temporary.path is defined
