version: "3.7"

services:

  # https://hub.docker.com/r/portainer/portainer
  portainer:
    container_name: "portainer"
    image: "portainer/portainer:${PORTAINER_VERSION}"
    ports:
      # UI/Portainer API/Polling
      - "9000:9000"
      # SSH tunnel server used to create a secure tunnel between the agent and the Portainer instance.
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: