version: "3.7"

services:

  # Smallest base system; as a scratch file - to keep composer valid
  scratch:
    image: alpine:3.10.3
  
  # https://hub.docker.com/_/traefik
  # traefik:
  #   container_name: traefik
  #   image: traefik:v2.0.4

  # https://hub.docker.com/_/memcached
  # memcached:
  #   container_name: memcached
  #   image: memcached:1.5.19

  # https://hub.docker.com/_/haproxy
  # haproxy:
  #   container_name: haproxy
  #   image: haproxy:1.9.12

  # https://hub.docker.com/_/redis
  # redis:
  #   container_name: redis
  #   image: redis:5.0.6

networks:
  default:
    name: traffic
  external:
    name: internal