- name: "Deploy CSI: NFS"
  import_tasks: nfs.yml
  tags:
    - nfs
- name: Install Rook/Ceph CSI
  tags:
    - ceph
  import_tasks: ceph.yml
- name: Set up local ZFS CSI
  tags:
    - zfs
  import_tasks: zfs.yml
