---
- name: Install local dependencies
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: Install ansible galaxy modules
      command: "ansible-galaxy collection install --upgrade {{ item }}"
      with_items:
        - ansible.posix
        - community.general
        - kubernetes.core
    - name: Intall Python packages
      command: "pip3 install {{ item }}"
      with_items:
        - "ansible-lint"
    - name: Install APT packages
      become: true
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - yamllint
...
