# ansible-galaxy collection install community.general ansible.posix kubernetes.core
---
- name: Set up Kubernetes cloud
  # gather_facts: true
  hosts: all
  roles:
   - baremetal
   - baremetal-opensearch
   - baremetal-containerd
   - baremetal-kubernetes
   - cni
   - tools
   - csi
   - loadbalancer
   - externaldns
   - ingress
   - dns
   - ldap
   - certmanager
   # Nexus
   #  Setup nexus here
   - argocd
   - vault

   # Via argo
   - gerrit
   # Load bootstrap projects
   - dashboard
   - monitoring
   # TODO: Allow for replays
   - jenkins
   - mongodb
   - kafka

## CERTS=/opt/bitnami/etcd/certs/client; etcdctl --cacert=${CERTS}/ca.pem --key=${CERTS}/client-key.pem --cert=${CERTS}/client.pem get / --prefix
