# ansible-galaxy collection install community.general ansible.posix kubernetes.core
---
- name: Set up Kubernetes cloud
  # gather_facts: true
  hosts: all
  roles:
   - baremetal
   - baremetal-elasticsearch
   - baremetal-containerd
   - baremetal-kubernetes
   - cni
   - tools
   - csi
   - loadbalancer
   - externaldns
   - ingress
   - dashboard
   - ldap
   - monitoring
   - certmanager
   - gerrit
   # TODO: Allow for replays
   - jenkins
   - argocd

## CERTS=/opt/bitnami/etcd/certs/client; etcdctl --cacert=${CERTS}/ca.pem --key=${CERTS}/client-key.pem --cert=${CERTS}/client.pem get / --prefix
