server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: vault.home.arpa
    tls:
      - secretName: vault-tls
        hosts:
          - vault.home.arpa
