serviceAccount:
  create: true
rbac:
  pspEnable: true
isClusterService: false
extraSecrets:
  - name: etcd-client-tls
    mountPath: /etc/coredns/tls/etcd
servers:
  - zones:
      - zone: .
    port: 53
    plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: etcd
        parameters: internal
        configBlock: |-
          stubzones
          path /skydns
          endpoint https://etcd-headless:2379
          tls /etc/coredns/tls/etcd/etcd-client.pem /etc/coredns/tls/etcd/etcd-client-key.pem /etc/coredns/tls/etcd/etcd-ca.pem
