- kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  with_items:
    - name: stable
      url: https://charts.helm.sh/stable
    - name: cetic
      url: https://cetic.github.io/helm-charts
- kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true
- kubernetes.core.helm:
    name: "{{ item.name }}"
    create_namespace: true
    chart_ref: "{{ item.chartRef }}"
    release_namespace: "{{ ldap.namespace }}"
    values: "{{ lookup('template', './ldap-{{ item.name }}.yml') | from_yaml }}"
  with_items:
    - name: "{{ ldap.phpldapadmin.releaseName }}"
      chartRef: cetic/phpldapadmin
    - name: "{{ ldap.openldap.releaseName }}"
      chartRef: stable/openldap
- kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: phpldapadmin-ingress
        namespace: "{{ ldap.namespace }}"
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: ca-issuer
      spec:
        rules:
          - host: "ldap-admin.{{ tld_hostname }}"
            http:
              paths:
                - backend:
                    service:
                      name: "{{ ldap.phpldapadmin.releaseName }}"
                      port:
                        number: 80
                  pathType: ImplementationSpecific
        tls:
          - hosts:
              - "ldap-admin.{{ tld_hostname }}"
            secretName: ldap-admin-tls
