

### List Projects

GET {{gerritUrl}}/a/projects/?d
Authorization: Basic {{username}} {{password}}

### Get Project

GET {{gerritUrl}}/a/projects/{{project-name}}
Authorization: Basic {{username}} {{password}}

### List Branches

GET {{gerritUrl}}/a/projects/{{project-name}}/branches
Authorization: Basic {{username}} {{password}}

### Get Branch

GET {{gerritUrl}}/a/projects/{{project-name}}/branches/HEAD
Authorization: Basic {{username}} {{password}}

### Get Branch

GET {{gerritUrl}}/a/projects/{{project-name}}/branches/{{ commit-id }}
Authorization: Basic {{username}} {{password}}

### Get file from branch

GET http://localhost:1555/a/projects/Example-Project/branches/refs%2Fheads%2Fmain/files/.pipeline%2Fworkflows%2Fexample.yaml/content
Authorization: Basic {{username}} {{password}}

### List Tags
### TODO: Use with versioning

GET {{gerritUrl}}/a/projects/{{project-name}}/tags
Authorization: Basic {{username}} {{password}}

### Limit(n)

GET {{gerritUrl}}/a/projects/{{project-name}}/tags?n=2
Authorization: Basic {{username}} {{password}}

### Substring(m)

GET {{gerritUrl}}/a/projects/{{project-name}}/tags?m=v
Authorization: Basic {{username}} {{password}}

### Regex(r)

GET {{gerritUrl}}/a/projects/{{project-name}}/tags?r=v.*
Authorization: Basic {{username}} {{password}}

### Get Commit

GET {{gerritUrl}}/a/projects/{{project-name}}/commits/{{commit-id}}
Authorization: Basic {{username}} {{password}}

### List Files

GET {{gerritUrl}}/a/projects/{{project-name}}/commits/{{commit-id}}/files/
Authorization: Basic {{username}} {{password}}

### Query Changes

GET {{gerritUrl}}/a/changes/
Authorization: Basic {{username}} {{password}}

### Get Change
### TODO: !SSH

GET {{gerritUrl}}/a/changes/{{change-id}}?o=ALL_REVISIONS
Authorization: Basic {{username}} {{password}}

### Get Change Detail

GET {{gerritUrl}}/a/changes/{{change-id}}/detail?o=ALL_REVISIONS
Authorization: Basic {{username}} {{password}}

### Get Commit
### TODO: !Author, commiter

GET {{gerritUrl}}/a/changes/{{change-id}}/revisions/{{revision-id}}/commit
Authorization: Basic {{username}} {{password}}

### List Files
### TODO: !Use with events

GET {{gerritUrl}}/a/changes/{{change-id}}/revisions/{{revision-id}}/files
Authorization: Basic {{username}} {{password}}

### List Robot Comments

GET {{gerritUrl}}/a/changes/{{change-id}}/revisions/{{revision-id}}/robotcomments
Authorization: Basic {{username}} {{password}}
Content-Type: application/json; charset=UTF-8

### Delete Comment

DELETE {{gerritUrl}}/a/changes/{{change-id}}/revisions/{{revision-id}}/comments/{{comment-id}}
Authorization: Basic {{username}} {{password}}
Content-Type: application/json; charset=UTF-8

### Set Review
### TODO: Use with actions, sarif
### TODO: Set reviews

POST {{gerritUrl}}/a/changes/{{change-id}}/revisions/{{revision-id}}/review
Authorization: Basic {{username}} {{password}}
Content-Type: application/json; charset=UTF-8

{
  "tag": "pmd",
  "message": "Result of a PMD test",
  "labels": {
    "Code-Review": -1
  },
  "robot_comments": {
    "/COMMIT_MSG": [
      {
        "side": "REVISION",
        "range": {
          "start_line": 1,
          "start_character": 2,
          "end_line": 1,
          "end_character": 4
        },
        "message": "Test first line comment comment",
        "robot_id": "PMD",
        "robot_run_id": "123",
        "fix_suggestions": [
          {
            "description": "Suggestion description",
            "replacements": [
              {
                "path": "/COMMIT_MSG",
                "range": {
                  "start_line": 7,
                  "start_character": 0,
                  "end_line": 7,
                  "end_character": 0
                },
                "replacement": "JIRA-XXXX"
              }
            ]
          }
        ]
      },
      {
        "side": "REVISION",
        "line": 0,
        "message": "Test file comment",
        "robot_id": "PMD",
        "robot_run_id": "123",
        "gerritUrl": "http://sss"
      }
    ]
  }
}

### Get OAuth Access Token

GET {{gerritUrl}}/a/accounts/self/oauthtoken
Authorization: Basic {{username}} {{password}}
