apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-kubectl
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cicd
rules:
  - apiGroups: [""]
    resources:
      - pods
      - configmaps
      - deployments
      - replicasets
      - statefulsets
      - ingresses
      - services
    verbs:
      - create
      - delete
      - deletecollection
      - patch 
      - update
      - list
      - get
  - apiGroups: [""]
    resources:
      - secrets
      - namespaces
    verbs:
      - create
      - patch 
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: jenkins-kubectl-cicd
subjects:
- kind: ServiceAccount
  name: jenkins-kubectl
  namespace: jenkins
roleRef:
  kind: ClusterRole
  name: cicd
  apiGroup: rbac.authorization.k8s.io
---
  