apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: monitoring
data:
  kubernetes-dashboards.yaml: |
    apiVersion: 1
    providers:
      # <string> an unique provider name
    - name: 'a unique provider name 2'
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string, required> name of the dashboard folder. Required
      folder: 'kubernetes'
      # <string, required> provider type. Required
      type: file
      # <bool> disable dashboard deletion
      disableDeletion: false
      # <bool> enable dashboard editing
      editable: true
      # <int> how often Grafana will scan for changed dashboards
      updateIntervalSeconds: 10
      # <bool> allow updating provisioned dashboards from the UI
      allowUiUpdates: false
      options:
        # <string, required> path to dashboard files on disk. Required
        path: /var/lib/grafana/dashboards/kubernetes
  prometheus-dashboards.yaml: |
    apiVersion: 1
    providers:
      # <string> an unique provider name
    - name: 'a unique provider name'
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string, required> name of the dashboard folder. Required
      folder: 'prometheus'
      # <string, required> provider type. Required
      type: file
      # <bool> disable dashboard deletion
      disableDeletion: false
      # <bool> enable dashboard editing
      editable: true
      # <int> how often Grafana will scan for changed dashboards
      updateIntervalSeconds: 10
      # <bool> allow updating provisioned dashboards from the UI
      allowUiUpdates: false
      options:
        # <string, required> path to dashboard files on disk. Required
        path: /var/lib/grafana/dashboards/prometheus
  general-dashboards.yaml: |
    apiVersion: 1
    providers:
      # <string> an unique provider name
    - name: 'a unique provider name 3'
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string, required> name of the dashboard folder. Required
      folder: ''
      # <string, required> provider type. Required
      type: file
      # <bool> disable dashboard deletion
      disableDeletion: false
      # <bool> enable dashboard editing
      editable: true
      # <int> how often Grafana will scan for changed dashboards
      updateIntervalSeconds: 10
      # <bool> allow updating provisioned dashboards from the UI
      allowUiUpdates: false
      options:
        # <string, required> path to dashboard files on disk. Required
        path: /var/lib/grafana/dashboards/general
  datasources.yaml: |
    # config file version
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: Graphite
        orgId: 1

    # list of datasources to insert/update depending
    # what's available in the database
    datasources:
    - name: docker-local
      type: grafana-kubernetes-datasource
      access: proxy
      url: https://kubernetes.docker.internal:6443
      basicAuth: false
      isDefault: false
      readOnly: false
      jsonData:
        ds: Prometheus
        tlsAuth: true
        tlsAuthWithCACert: true
      secureJsonData:
        tlsCACert: |
          -----BEGIN CERTIFICATE-----
          MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
          cm5ldGVzMB4XDTE5MTIxMzIwMTIxMloXDTI5MTIxMDIwMTIxMlowFTETMBEGA1UE
          AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKjb
          4yyQwiMAV/PMl579RvGxnjb+wZNjY4onUi0UND21Sywduj8ErHEPdIwIMFeA3bP5
          Z3blerdoUx4iCnEeV0gOfaYezEDkbzmEU/KK03QKHdR9HU9WOlBuDXIrcebD9sfV
          QPu7xfFlFpkelMJDVEG7H1DlwNVMkKd69nFAGXZXRsTjGSqdzAexy7hHC67fHm7L
          JOdSeEED8lfTFpIPV4DdaEs+Pmg5y8gRMRr+PtnD/AL8RzY7ruztyCvdCql1p61M
          RCMgrftZhPxe4cRO59xAt9reSBW6T5mt39zfY8L8YsrYkVLjcGCxUmm/vqYUnwkv
          X7pSawN2dPVPcLOz+x0CAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
          /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAC+8ddHjapg6vQDPVrJH4tbZcEW6
          RM5h7TrDlZjF/0w/OOvVwgmwpyg30GsFLBqgCyeoRPI6pfiYWz5VVBzIzCOH4Cey
          isYba4VnDNd4WxXG+6bxGVmdWer+Tr5d/NNCaTUTYa4Fln71WEKUgAbqLZOZ7ba8
          up1shVMqQrbYT6knZNv7aktiHVEroZmoLdD0973vyJvg2IRhCkK29jn+2G6Ly1FV
          rA8hnd4xZqMsqKpaj73xCMu8rhb24xJDG4d+f6RdeqL3CETxlU05PBkpgBF33NRJ
          rrM9TH4IKvhUCJsOPAuJvaQsDouAZC+wKLvMHpjRjRHFgU7ML/1Wl6kX4Hg=
          -----END CERTIFICATE-----
        tlsClientCert: |
          -----BEGIN CERTIFICATE-----
          MIIC9DCCAdygAwIBAgIIB9lan4UdjFQwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
          AxMKa3ViZXJuZXRlczAeFw0xOTEyMTMyMDEyMTJaFw0yMTAyMjgyMTIyNTJaMDYx
          FzAVBgNVBAoTDnN5c3RlbTptYXN0ZXJzMRswGQYDVQQDExJkb2NrZXItZm9yLWRl
          c2t0b3AwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAS16KoyGicHgw
          YNR4GYZrM7mZApumnCBOJAUhDgLNpk6grR8Mz/VpQFvfMbA17z35K3CGpl8XwK2s
          Fzh1I/AjrbiUbbuS9WDlqd7+nMGk8emgP1wlDzrms6Gyg6vvRFR3LwmvsndYDane
          0tshliPslNpPNafE5431WSjeMLfTKLXVen3SxQl6zQRl+E6RUkEOAArLJQHUyYGO
          Gh7CAvG1oxlmKw+2hDBtK0JguL/VUWnuh4lXko6In3o5vD64iGdTRW62n9wYXCvE
          4HxuMsmojxe9nzii2jfuTbq/Ty7fZV+jDDz95H3y2juVv4D8LsrgKF30C2CQbieu
          lzbdUOxDAgMBAAGjJzAlMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEF
          BQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAG1aA6poO1vJCq3O/Fb5doHdr3ADswt6n
          aIgt6JBCd7S3Z1W3HuSjsFVkmG2y1+aY3Ci8arYBGMA0zdn2+WAu5Nj+Qz6APVpf
          3Qz2K7gmQEc7M+8Xug7Rb5VLb9oyXvtdkfKlYHRZ9BFLH8N5UiCB6k5OWns+XmDv
          zy4Dul7UCQ1WvvIil7mE8zIfbuqy+sX7EZ1FgToF3CGWyIono8hFsGcdtKkCqhnV
          IuRm2fJKknBjKI/El0TyZafzvskBbBF6OEVie4Kn15K0ZztkF6Ix5rTOnWRV4XTq
          GhZKfkgs5fvCoXqcPWLE8q2KUleKtKRoakYcecheH6CQb7+o1fgHUQ==
          -----END CERTIFICATE-----
        tlsClientKey: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpQIBAAKCAQEAwEteiqMhonB4MGDUeBmGazO5mQKbppwgTiQFIQ4CzaZOoK0f
          DM/1aUBb3zGwNe89+StwhqZfF8CtrBc4dSPwI624lG27kvVg5ane/pzBpPHpoD9c
          JQ865rOhsoOr70RUdy8Jr7J3WA2p3tLbIZYj7JTaTzWnxOeN9Vko3jC30yi11Xp9
          0sUJes0EZfhOkVJBDgAKyyUB1MmBjhoewgLxtaMZZisPtoQwbStCYLi/1VFp7oeJ
          V5KOiJ96Obw+uIhnU0Vutp/cGFwrxOB8bjLJqI8XvZ84oto37k26v08u32Vfoww8
          /eR98to7lb+A/C7K4Chd9AtgkG4nrpc23VDsQwIDAQABAoIBAGjQ7HCvaScNHUZp
          kYcBitamdDVmSYewtJ9DXRReecK1M0i79R/bv06myS1I/V740JQgTI7o4w6kdUZH
          xft8ImqgR+uIQOVjIXUueiHZOmh5gLpbrxN4UMfuBGa1BSQ/37azihkeM5VopT6T
          OuT83QoZPUJN4ewft66T8gXjEmBjb4+HTqzGgTooZAB+Gl3wUAYQxNQ3JzdMSRVu
          lWDXdWrSAWO/fPvdrwtqSi7X3spo6j2jyKGpX+7JzPw1W1yfTP8QNlMBm5A2XrKt
          agA4uAEwi9idTYDfIEefZ1WMX+2eG7hJIL78rgIprTLey04o8mKUFXxsiSnAEkNA
          jjIrI9kCgYEA30ME0nQ16480XCO+imjkhPFY52o7CT/4fhUMsb6hc46gePm1MF0W
          /TJCeGXr8cLnf1KMdc1r9PFdOKuRX0Klapd4Wli0B1Lqrk1fxJRtDk39CUbgrLJo
          ajcW3BR3xK70bWGKbvtfg11f/8/N5/TZxoctQOIfSbVV134GFc4b1v8CgYEA3H3f
          ODxcQ+AMDA6HDiYwGvYzRJDKs5pYX8iK+tvjh5wePJl8o6qO3iipYobXr5svCoCX
          V3chqlKof6TIHiwppjLRE1cton5/dwYlb8+bAUo2lDwwFKmztA4dVF+VZVhK3p4W
          xPVCQtXN00G2TY3TlVpYp3fa1f322pqBxMY+zr0CgYEApJeo52orEjUp2b+0Sh/Y
          ULYI39ouGbyienkUObmbFzEP1v/odvY564HxBQfGsR4KQpBd4r8FlreWDSBW9M6S
          Wom+fYSlfDzBrKx4LNlrqL8QC5XILyj710ozvR4Nyd9dbYIaZ4VEPflJu7K8TwPw
          xO6FCy9o95MK7OoInGytk4sCgYEAqzhjuvvEekDlmgc+AVLOUGGXdksp3UaiEd9d
          bWiLy6cEI/LcwwuTXhkdUBF+NDPB19n7rEQqtGTzzAteC3An95PGn8o2+dRZj0gK
          kkUZDWtf7sS+YY1Wqx+6zuZa0RQ7L5x7+f6qsdPtvXtt4dOc1oIODh4YpcxNgXwy
          AWghJdECgYEAgvAs8MnVdUMNFlXEBG9/IsFdFUlyTH4l/ggDQ5u9v+YUEtumON3K
          N/uzu5tgnOBDt/3W1RDJ/NfuL42KfCGi9wdiBG1SUyDGc+TQjWBYdy1HLSR1hNzv
          AVsNEmq2LVEKedDFL5WoytEMpBgiKfqr73nl9tPnhoWL3TYp784kk0Y=
          -----END RSA PRIVATE KEY-----
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      basicAuth: false
      isDefault: true
      readOnly: false
      jsonData: {}
