kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    component: "grafana-container"
  ports:
    - port: 3000
      nodePort: 31005
      name: http
