provider: coredns
policy: sync
#namespace: "{{ externaldns.namespace }}"
logLevel: debug
coredns:
  etcdEndpoints: "https://etcd:2379"
  etcdTLS:
    enabled: true
    certFilename: client.pem
    keyFilename: client-key.pem
    caFilename: ca.pem
    secretName: etcd-client-tls