connectors:
- type: ldap
  name: OpenLDAP
  id: ad
  config:
    # Ldap server address
    host: "{{ldap.server}}:{{ldap.port}}"
    insecureNoSSL: true
    insecureSkipVerify: true
    # Variable name stores ldap bindDN in argocd-secret
    bindDN: "$dex.ldap.bindDN"
    # Variable name stores ldap bind password in argocd-secret
    bindPW: "$dex.ldap.bindPW"
    usernamePrompt: Username
    # Ldap user serch attributes
    userSearch:
      baseDN: "ou=people,dc=home,dc=arpa"
      filter: "(objectClass=inetOrgPerson)"
      username: uid
      idAttr: uid
      emailAttr: mail
      nameAttr: sn
    # Ldap group serch attributes
    groupSearch:
      baseDN: "ou=groups,dc=home,dc=arpa"
      filter: "(objectClass=posixGroup)"
      userMatchers:
        - userAttr: uid
          groupAttr: memberuid
      nameAttr: cn
