server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
    #  external-dns.alpha.kubernetes.io/hostname: "argocd.{{ tld_hostname }}"
    hosts:
      - argo.home.arpa
    tls:
      - secretName: argo-tls
        hosts:
          - argo.home.arpa
configs:
  cm:
    url: "https://argo.home.arpa"