version: '3.8'
services:
  docker:
    volumes:
      - certs:/certs
    privileged: true
    image: docker:20.10.0-rc2-dind
  docker-client:
    depends_on:
      - docker
    image: docker:20.10.0-rc2
    command: 'sleep infinity'
    volumes:
      - certs:/certs:ro
      - .:/workdir
volumes:
  certs:
networks:
  build:
#docker exec -it $(docker ps | grep docker-client | awk '{print $1}') ash
