credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          description: "Default gerrit"
          id: "gerrit"
          privateKeySource:
            directEntry:
              privateKey: |
                {% filter indent(width=16,blank=True) -%}
                {{sshkey.stdout}}
                {% endfilter %}
          scope: GLOBAL
          username: "jenkins"
