unclassified:
  globalTimeOutConfiguration:
    strategy:
      absoluteTimeOutStrategy:
        timeoutMinutes: "15"
  scmGit:
    showEntireCommitSummaryInChanges: true
  timestamper:
    allPipelines: true
  globalLibraries:
    libraries:
      - name: "shared"
        defaultVersion: "main"
        retriever:
          modernSCM:
            scm:
              git:
                credentialsId: "gerrit"
                remote: "{{ gerrit.sshUrl }}/Jenkins-Libraries"
                traits:
                  - "gitBranchDiscovery"
