jenkins:
  authorizationStrategy: "loggedInUsersCanDoAnything"
  securityRealm:
    ldap:
      configurations:
        - displayNameAttributeName: cn
          inhibitInferRootDN: false
          managerDN: 'cn={{jenkins.ldap.user}},{{jenkins.ldap.root_dn}}'
          managerPasswordSecret: '{{jenkins.ldap.password}}'
          rootDN: '{{jenkins.ldap.root_dn}}'
          server: '{{jenkins.ldap.server}}'
      disableMailAddressResolver: false
      disableRolePrefixing: true
      groupIdStrategy: caseInsensitive
      userIdStrategy: caseInsensitive
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
