apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-namespace

commonLabels:
  ventheAppIdentifier: nexus

secretGenerator:
  - name: nexus-secret
    type: Opaque
    files:
    - secrets/security.xml

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: nexus-service
  path: nexus-service-patch.yaml

images:
  - name: sonatype/nexus3
    newTag: 3.28.0

resources:
  - manifests/namespace.yaml
  - manifests/nexus.yaml
