kind: Service
apiVersion: v1
metadata:
  name: nexus-service
  labels:
    app: nexus
spec:
  type: NodePort
  selector:
    app: nexus
    component: nexus
  ports:
    - port: 8081
      nodePort: 31010
      name: http

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus-statefulset
  labels:
    app: nexus
spec:
  serviceName: nexus-service
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
        component: nexus
    spec:
      containers:
        # https://hub.docker.com/r/sonatype/nexus3
        - name: nexus-container
          ports:
            - containerPort: 8081
          image: sonatype/nexus3:3.23.0
          volumeMounts:
            - name: nexus-data-persisstentvolumeclaim
              mountPath: /nexus-data
  volumeClaimTemplates:
    - metadata:
        name: nexus-data-persisstentvolumeclaim
        labels:
          app: nexus
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
