name: Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: docker.io/venthe/ubuntu-runner:22.10
    steps:
      - uses: actions/git-checkout@v1
      - run: ls
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Show java
        run: java --version
      - uses: actions/setup-gradle@v1
        with:
          version: '7.4.2'
      - uses: actions/setup-docker@v1
        name: Install docker
      - run: gradle bootJar --no-daemon --console=plain
      - run: docker build .
