controller:
  ingress:
    enabled: true
    # Override for the default paths that map requests to the backend
    paths: []
    # - backend:
    #     serviceName: ssl-redirect
    #     servicePort: use-annotation
    # - backend:
    #     serviceName: >-
    #       {{ template "jenkins.fullname" . }}
    #     # Don't use string here, use only integer value!
    #     servicePort: 8080
    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    apiVersion: "extensions/v1beta1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    # Set this path to jenkinsUriPrefix above or use annotations to rewrite path
    # path: "/jenkins"
    # configures the hostname e.g. jenkins.example.com
    hostName: jenkins.example.org
    # tls:
    # - secretName: jenkins.cluster.local
    #   hosts:
    #     - jenkins.cluster.local
  additionalPlugins:
    - timestamper:1.11.8
    - ldap:1.26
    - gerrit-trigger:2.121.1
  prometheus.enabled: true
  servicePort: 80
  jenkinsUrl: http://jenkins.example.org/
  initializeOnce: false
  JCasC:
    configScripts:
      security: |
        jenkins:
          agentProtocols:
            - JNLP4-connect
            - Ping
          authorizationStrategy:
            loggedInUsersCanDoAnything
          labelAtoms:
            - name: master
          myViewsTabBar: standard
          primaryView:
            all:
              name: all
          quietPeriod: 5
          scmCheckoutRetryCount: 0
          slaveAgentPort: 50000
          updateCenter:
            sites:
              - id: default
                url: 'https://updates.jenkins.io/update-center.json'
          views:
            - all:
                name: all
          viewsTabBar: standard
          securityRealm:
            ldap:
              configurations:
                - displayNameAttributeName: cn
                  inhibitInferRootDN: false
                  managerDN: 'cn=readonly,dc=example,dc=org'
                  managerPasswordSecret: '{AQAAABAAAAAQd9JDgVMOkS8Kd7Xvzu97byGo5vRGA8iuqN+GT35Lofw=}'
                  rootDN: 'dc=example,dc=org'
                  server: openldap.ldap
              disableMailAddressResolver: false
              disableRolePrefixing: true
              groupIdStrategy: caseInsensitive
              userIdStrategy: caseInsensitive
        unclassified:
          buildDiscarders:
            configuredBuildDiscarders:
              - jobBuildDiscarder
          fingerprints:
            fingerprintCleanupDisabled: false
            storage: file
          gitSCM:
            allowSecondFetch: false
            createAccountBasedOnEmail: false
            disableGitToolChooser: false
            hideCredentials: false
            showEntireCommitSummaryInChanges: false
            useExistingAccountWithSameEmail: false
          junitTestResultStorage:
            storage: file
          mailer:
            charset: UTF-8
            useSsl: false
            useTls: false
          pollSCM:
            pollingThreadCount: 10
          timestamper:
            allPipelines: false
            elapsedTimeFormat: '''<b>''HH:mm:ss.S''</b> '''
            systemTimeFormat: '''<b>''HH:mm:ss''</b> '''
        tool:
          git:
            installations:
              - home: git
                name: Default

