---
- name: Install coreDNS
  gather_facts: false
  hosts: all
  vars_prompt:
    - name: deployment_namespace
      default: external-dns
      private: false
    - name: tld_hostname
      default: home.arpa
      private: false
    - name: delete_namespace
      default: false
      private: false
    - name: chown_user
      default: vagrant
      private: false
  tasks:
    - name: Delete namespace
      command: "kubectl delete namespace {{ deployment_namespace }}"
      when: "delete_namespace|bool"
    - name: copy manifests
      become: true
      copy:
        src: ./manifest/
        dest: /tmp/
        directory_mode: yes
        mode: 0777
        owner: '{{ chown_user }}'
    - name: Template manifests
      become: true
      template:
        src: "./template/{{ item }}"
        dest: "/tmp/{{ item }}"
        owner: '{{ chown_user }}'
        mode: '0777'
      with_items:
        - cilium-etcd-operator.yaml
        - coredns-values.yml
        - external-dns-values.yaml
        - load-balancer.yml
    - name: Add helm repository
      command: "helm repo add {{ item.name }} {{ item.url }}"
      with_items:
        - name: stable
          url: https://charts.helm.sh/stable
        - name: bitnami
          url: https://charts.bitnami.com/bitnami
    - name: Update helm repositories
      command: helm repo update
    - name: Install coredns helm chart
      shell:
        cmd: |
          helm upgrade \
            --install \
            --create-namespace \
            --namespace={{ deployment_namespace }} \
            --values=/tmp/coredns-values.yml \
            coredns \
            stable/coredns
    - name: Apply manifests
      command: "kubectl apply -f /tmp/{{ item }}"
      with_items:
        - etcd-crd.yaml
        - cilium-etcd-operator.yaml
    - name: Install etcd cluster helm chart
      shell:
      # Namespace kube-system?
        cmd: |
          helm upgrade \
            --install \
            --create-namespace \
            --set=customResources.createEtcdClusterCRD=true \
            --namespace={{ deployment_namespace }} \
            my-etcd-op \
            stable/etcd-operator
    - name: Install ExternalDNS Container helm chart
      shell:
        cmd: |
          helm upgrade \
            --install \
            --create-namespace \
            --values=/tmp/external-dns-values.yaml \
            --namespace={{ namespace }} \
            external-dns \
            bitnami/external-dns
    - name: Expose DNS service
      command: "kubectl apply -f /tmp/load-balancer.yml"
