apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  ventheAppIdentifier: monitoring

namespace: monitoring-namespace

configMapGenerator:
  - name: prometheus-config
    files:
      - configMaps/prometheus/prometheus.yml
  - name: grafana-dashboards-kubernetes
    files:
      - configMaps/grafana/dashboards/K8s-Cluster.json
      - configMaps/grafana/dashboards/K8s-Container.json
      - configMaps/grafana/dashboards/K8s-Deployments.json
      - configMaps/grafana/dashboards/K8s-Node.json
  - name: grafana-dashboards-general
    files:
      - configMaps/grafana/dashboards/Grafana-metrics.json
  - name: grafana-dashboards-prometheus
    files:
      - configMaps/grafana/dashboards/Prometheus-2.0-Stats.json
      - configMaps/grafana/dashboards/Prometheus-Stats.json
  - name: grafana-provisioning
    files:
      - configMaps/grafana/provisioning/plugins.yaml
      - configMaps/grafana/provisioning/dashboards-kubernetes.yaml
      - configMaps/grafana/provisioning/dashboards-prometheus.yaml
      - configMaps/grafana/provisioning/dashboards-general.yaml


secretGenerator:
  - name: grafana-secret
    type: Opaque
    env: secrets/grafana/password.txt
  - name: grafana-datasources
    type: Opaque
    files:
      - secrets/grafana/datasources.yaml


patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: prometheus-service
    path: prometheus-service-patch.yaml
  - target:
      version: v1
      kind: Service
      name: grafana-service
    path: grafana-service-patch.yaml

resources:
  - manifests/0.monitoring-namespace.yaml
  - manifests/1.prometheus-rbac.yaml
  - manifests/3.prometheus-service.yaml
  - manifests/4.prometheus-deployment.yaml
  - manifests/7.grafana-service.yaml
  - manifests/8.grafana-deployment.yaml
  - manifests/11.state-metrics-rbac.yaml
