apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipeline-mediator.fullname" . }}
  labels:
    {{- include "pipeline-mediator.labels" . | nindent 4 }}
data:
  application.yaml: |
    {{- toYaml .Values.configMap | nindent 4 }}
