apiVersion: v1
kind: Service
metadata:
  name: ldapadmin-service
  labels:
    app: ldapadmin
spec:
  type: LoadBalancer
  selector:
    component: ldapadmin
    app: ldapadmin
  ports:
    - port: 80
      name: http
    - port: 443
      name: https

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldapadmin-deployment
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldapadmin
  template:
    metadata:
      labels:
        app: ldapadmin
        component: ldapadmin
    spec:
      containers:
        # https://github.com/osixia/docker-phpLDAPadmin
        - name: ldapadmin-container
          image: osixia/phpldapadmin:0.9.0
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "ldap-service"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"