apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  labels:
    app: ldap
spec:
  selector:
    component: ldap
    app: ldap
  ports:
    - port: 389
      name: ldap
    - port: 636
      name: ldaps
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldap-statefulset
  labels:
    app: ldap
spec:
  serviceName: ldap-service
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
        component: ldap
    spec:
      volumes:
        - name: ldap-bootstrap
          configMap:
            name: ldap-bootstrap
      containers:
        - name: ldap-container
          ports:
            - containerPort: 389
              protocol: TCP
            - containerPort: 636
              protocol: TCP
          # https://github.com/osixia/docker-openldap
          image: osixia/openldap:1.4.0
          env:
            - name: LDAP_READONLY_USER
              valueFrom:
                configMapKeyRef:
                  name: ldap-config
                  key: LDAP_READONLY_USER
            - name: LDAP_READONLY_USER_USERNAME 
              valueFrom:
                secretKeyRef:
                  name: ldap-secret
                  key: LDAP_READONLY_USER_USERNAME
            - name: LDAP_READONLY_USER_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: ldap-secret
                  key: LDAP_READONLY_USER_PASSWORD
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-secret
                  key: LDAP_ADMIN_PASSWORD
            - name: LDAP_ORGANISATION
              valueFrom:
                configMapKeyRef:
                  name: ldap-config
                  key: LDAP_ORGANISATION
            - name: LDAP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: ldap-config
                  key: LDAP_DOMAIN
            - name: LDAP_TLS
              value: "false"
          args:
              - "--copy-service"
          volumeMounts:
            - name: openldap-var-lib-ldap-persistentvolumeclaim
              mountPath: /var/lib/ldap
            - name: openldap-etc-ldap-slapd-d-persistentvolumeclaim
              mountPath: /etc/ldap/slapd.d
            # Add
            # - name: ldap-bootstrap
            #   mountPath: /container/service/slapd/assets/config/bootstrap/ldif
            # Modify
            - name: ldap-bootstrap
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom/export.ldif
              subPath: export.ldif
  volumeClaimTemplates:
    - metadata:
        name: openldap-var-lib-ldap-persistentvolumeclaim
        labels:
          app: ldap
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
    - metadata:
        name: openldap-etc-ldap-slapd-d-persistentvolumeclaim
        labels:
          app: ldap
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
