---
- name: Deploy LDAP
  gather_facts: false
  hosts: all
  vars:
    LDAP_BASE_DN: "{{'{{ LDAP_BASE_DN }}'}}"
    LDAP_DOMAIN: "{{'{{ LDAP_DOMAIN }}'}}"
    LDAP_READONLY_USER_USERNAME: "{{'{{ LDAP_READONLY_USER_USERNAME }}'}}"
    LDAP_READONLY_USER_PASSWORD_ENCRYPTED: "{{'{{ LDAP_READONLY_USER_PASSWORD_ENCRYPTED }}'}}"
    TEMP_PATH: "/tmp/ldap"
  vars_prompt:
    - name: chown_user
      prompt: linux user for chown
      default: vagrant
      private: no
    - name: namespace
      prompt: Namespace for LDAP
      default: ldap
      private: no
    - name: should_clear
      prompt: Clear before installing
      default: no
      private: no
    - name: admin_password
      default: "secret"
      prompt: Admin password
    - name: ldap_domain
      default: "home.arpa"
      prompt: LDAP domain
      private: no
    - name: ldap_organisation
      default: "My Company"
      private: no
      prompt: LDAP organisation
  tasks:
    - name: Delete old releases
      command: "helm uninstall --namespace {{ namespace }} {{ item }}"
      with_items:
        - phpldapadmin
        - openldap
      when: "should_clear|bool"
    - name: Create temporary directories
      become: true
      file:
        path: "{{ TEMP_PATH }}/{{ item }}"
        state: directory
      with_items:
        - openldap
        - phpldapadmin
    - name: Templating pass
      become: true
      template:
        src: "./{{item.path}}/{{item.filename}}.j2"
        dest: "{{ TEMP_PATH }}/{{item.path}}/{{item.filename}}"
        owner: "{{ chown_user }}"
        mode: '0777'
      with_items:
        - filename: values.yml
          path: phpldapadmin
        - filename: ingress.yml
          path: phpldapadmin
        - filename: values.yml
          path: openldap
    - name: Add helm repository
      command: "helm repo add {{ item.name }} {{ item.url }}"
      with_items:
        - name: stable
          url: https://charts.helm.sh/stable
        - name: cetic
          url: https://cetic.github.io/helm-charts
    - name: Update helm repositories
      command: helm repo update
    - name: Deploy helm charts
      shell:
        cmd: |
          helm upgrade --install \
            --namespace={{ namespace }} --create-namespace \
            --values={{ item.value }} \
            {{ item.release_name }} \
            {{ item.chart }}
      with_items:
        - release_name: phpldapadmin
          chart: cetic/phpldapadmin
          value: "{{ TEMP_PATH }}/phpldapadmin/values.yml"
        - release_name: openldap
          chart: stable/openldap
          value: "{{ TEMP_PATH }}/openldap/values.yml"
    - name: Apply ingress
      command: kubectl apply -f {{ TEMP_PATH }}/phpldapadmin/ingress.yml
    - name: Clean temp path
      become: true
      file:
        state: absent
        path: "{{ TEMP_PATH }}/"
