---
- name: Configure Gerrit on Kubernetes
  gather_facts: true
  become: false
  hosts: all
  vars_prompt:
    - name: namespace
      default: gerrit
      private: false
      prompt: Namespace of pod
  tasks:
    - kubernetes.core.kubectl:
        kubectl_namespace: "{{namespace}}"
        kubectl_pod: "{{namespace}}-gerrit-stateful-set-0"
        kubectl_extra_args: "pwd" 
...