apiVersion: v1
kind: Service
metadata:
  name: sonarqube-database-service
  labels:
    app: sonarqube
spec:
  selector:
    app: sonarqube
    component: sonarqube-database
  ports:
  - port: 5432
    name: pgsql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube-database-statefulset
  labels:
    app: sonarqube
spec:
  serviceName: sonarqube-database
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
        component: sonarqube-database
    spec:
      containers:
      # https://hub.docker.com/_/postgres
      - name: sonarqube-database
        image: postgres:13
        env:
          - name: POSTGRES_DB
            value: "sonarqube"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: sonarqube-secret
                key: postgresql_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sonarqube-secret
                key: postgresql_password
        volumeMounts:
         - name: sonarqube-database-data
           mountPath: /var/lib/postgresql/data"
  volumeClaimTemplates:
    - metadata:
        name: sonarqube-database-data
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "512Mi"
---