images:
  version: 3.3.0

gitGC:
  image: venthe/git-gc

gerrit:
  images:
    gerritInit: venthe/gerrit-init
    gerrit: venthe/gerrit

  livenessProbe:
    initialDelaySeconds: 30

  readinessProbe:
    initialDelaySeconds: 30

  startupProbe:
    initialDelaySeconds: 60

  sshd:
    enabled: true
    port: 29418

  plugins:
    packaged:
    - "commit-message-length-validator"
    - "download-commands"
    - "replication"
    - "reviewnotes"
    - "webhooks"
    - "gitiles"
    - "hooks"
    - "plugin-manager" 
    - "delete-project"
    - "codemirror-editor"
#  service:
#    type: "LoadBalancer"
  ingress:
    host: "gerrit.example.org"
  etc:
    config:
      gitiles.config: |
        [markdown]
            render = true
      project.config: |
        
      gerrit.config: |
        [gerrit]
            basePath = git # FIXED
            serverId = 08bdfaeb-f1f9-402c-9496-1aedbbde3b8a
            # The canonical web URL has to be set to the Ingress host, if an Ingress
            # is used. If a LoadBalancer-service is used, this should be set to the
            # LoadBalancer's external IP. This can only be done manually after installing
            # the chart, when you know the external IP the LoadBalancer got from the
            # cluster.
            canonicalWebUrl = http://gerrit.example.org/
            canonicalGitUrl = git://gerrit.example.org/
            disableReverseDnsLookup = true
            ui = POLYGERRIT
        [index]
            type = LUCENE
            onlineUpgrade = false # FIXED
        [auth]
            type = LDAP
        [ldap]
            server = ldap://openldap.ldap
        
            accountBase = ou=people,dc=example,dc=org
            accountPattern = (&(objectClass=inetOrgPerson)(uid=${username}))
            accountFullName = cn
            accountEmailAddress = mail
        
            groupBase = ou=groups,dc=example,dc=org
            groupMemberPattern = (&(objectClass=posixGroup)(memberUid=${username}))
        [httpd]
            # If using an ingress use proxy-http or proxy-https
            listenUrl = proxy-http://*:8080/
            requestLog = true
        [sshd]
            listenAddress = *:29418
            advertisedAddress = gerrit.example.org:29418
        [transfer]
            timeout = 120 s
        [user]
            name = Gerrit Code Review
            email = gerrit@my-company.com
            anonymousCoward = Unnamed User
        [cache]
            directory = cache
        [container]
            user = gerrit # FIXED
            javaHome = /usr/lib/jvm/java-1.8-openjdk # FIXED
            javaOptions = -Djavax.net.ssl.trustStore=/var/gerrit/etc/keystore # FIXED
            javaOptions = -Xms200m
            # Has to be lower than 'gerrit.resources.limits.memory'. Also
            # consider memories used by other applications in the container.
            javaOptions = -Xmx4g
    secret:
      secure.config: |
        [auth]
            registerEmailPrivateKey = m9HMpzcaWiqEUw7U+qE8y4iTG01CU3CspfY=
        [database]
            username = postgres
            password = Askiv4ViRfCUdiwT
        [ldap]
            username = cn=readonly,dc=example,dc=org
            password = readonly
            # Password for the keystore added as value for 'gerritReplica.keystore'
        # Only needed, if SSL is enabled.
        #[httpd]
        #  sslKeyPassword = gerrit
        
        # Credentials for replication targets
        # [remote "replica"]
        # username = git
        # password = secret
      ssh_host_ecdsa_384_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAiAAAABNlY2RzYS
        1zaGEyLW5pc3RwMzg0AAAACG5pc3RwMzg0AAAAYQS0uX2Uafq/ik0q/PVUokJQq55WDyiW
        eGhc0jo69hmt6sQ1QZ2c8ib/PQ4ID0YtrkW+c8laKbB1L52wxgfa4OSIoP5YS1jdbVtgYb
        5j7vTdl2aEboEKzLuuZ4mPP81zTVwAAADohphrAoaYawIAAAATZWNkc2Etc2hhMi1uaXN0
        cDM4NAAAAAhuaXN0cDM4NAAAAGEEtLl9lGn6v4pNKvz1VKJCUKueVg8olnhoXNI6OvYZre
        rENUGdnPIm/z0OCA9GLa5FvnPJWimwdS+dsMYH2uDkiKD+WEtY3W1bYGG+Y+703ZdmhG6B
        Csy7rmeJjz/Nc01cAAAAMHBssCc/2llSP7FGF5xqLplYDeHaQsuKcXI5YZ8QJr11Hi0ab2
        RJ1jqgZNcFRfZCEwAAAB9nZXJyaXQtY29kZS1yZXZpZXdAYTg1Nzc0M2JhYjBlAQ==
        -----END OPENSSH PRIVATE KEY-----
        
      ssh_host_ecdsa_384_key.pub: |
        ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBLS5fZRp+r+KTSr89VSiQlCrnlYPKJZ4aFzSOjr2Ga3qxDVBnZzyJv89DggPRi2uRb5zyVopsHUvnbDGB9rg5Iig/lhLWN1tW2BhvmPu9N2XZoRugQrMu65niY8/zXNNXA== gerrit-code-review@a857743bab0e
        
      ssh_host_ecdsa_521_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAArAAAABNlY2RzYS
        1zaGEyLW5pc3RwNTIxAAAACG5pc3RwNTIxAAAAhQQAHoUBFcRN5/UljUZFLNNCUIn0/ZvN
        F3LTr3gsjZSQsy7WtajiCC+CeC32wivLvaxuFXk24sjtygcHThkZPFBk3u4AnGlKtq2ov2
        84GODfYw7Elpc+Zq+33s+KOxXI7uzAn+CWjKYeM50P1qG5qWSBrCB7ZSdtBdOWryWEIkJd
        AtojW14AAAEgoinCg6IpwoMAAAATZWNkc2Etc2hhMi1uaXN0cDUyMQAAAAhuaXN0cDUyMQ
        AAAIUEAB6FARXETef1JY1GRSzTQlCJ9P2bzRdy0694LI2UkLMu1rWo4ggvgngt9sIry72s
        bhV5NuLI7coHB04ZGTxQZN7uAJxpSratqL9vOBjg32MOxJaXPmavt97PijsVyO7swJ/glo
        ymHjOdD9ahualkgawge2UnbQXTlq8lhCJCXQLaI1teAAAAQgFFi6BPS00RHvckEB4QIa7a
        WSFEpZVkKUzdFg4DxAuNtNM2y0AASRQv/39OcwvzRsnFhQVGP34axkq4nR+6jOJ7CAAAAB
        9nZXJyaXQtY29kZS1yZXZpZXdAYTg1Nzc0M2JhYjBlAQID
        -----END OPENSSH PRIVATE KEY-----
        
      ssh_host_ecdsa_521_key.pub: |
        ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAAehQEVxE3n9SWNRkUs00JQifT9m80XctOveCyNlJCzLta1qOIIL4J4LfbCK8u9rG4VeTbiyO3KBwdOGRk8UGTe7gCcaUq2rai/bzgY4N9jDsSWlz5mr7fez4o7Fcju7MCf4JaMph4znQ/WobmpZIGsIHtlJ20F05avJYQiQl0C2iNbXg== gerrit-code-review@a857743bab0e
        
      ssh_host_ecdsa_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
        1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQTJ8jAzy+IV01DnmNiHRq3R/TEJmO+/
        287FRJMhOLxjqeIgP2Da0hDDElmNcBrIZ5Qwy7M7Y5t6Jd4pV6Dk/GqNAAAAuIikoKqIpK
        CqAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMnyMDPL4hXTUOeY
        2IdGrdH9MQmY77/bzsVEkyE4vGOp4iA/YNrSEMMSWY1wGshnlDDLsztjm3ol3ilXoOT8ao
        0AAAAhAMdvEmVPVSapsz9rBxI/wQeU3orjQvdL/aayRTSsUf5/AAAAH2dlcnJpdC1jb2Rl
        LXJldmlld0BhODU3NzQzYmFiMGU=
        -----END OPENSSH PRIVATE KEY-----
        
      ssh_host_ecdsa_key.pub: |
        ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMnyMDPL4hXTUOeY2IdGrdH9MQmY77/bzsVEkyE4vGOp4iA/YNrSEMMSWY1wGshnlDDLsztjm3ol3ilXoOT8ao0= gerrit-code-review@a857743bab0e
        
      ssh_host_ed25519_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACCA/31EdxuNeJwrpOi0B5vPVKtaV0Iw/GnPe/TjPmMlYAAAAKjiH9rA4h/a
        wAAAAAtzc2gtZWQyNTUxOQAAACCA/31EdxuNeJwrpOi0B5vPVKtaV0Iw/GnPe/TjPmMlYA
        AAAEBYWFzCFlnXbS3bkJ/VaFxmfpNNylMl1vrVlKgnt07eXYD/fUR3G414nCuk6LQHm89U
        q1pXQjD8ac979OM+YyVgAAAAH2dlcnJpdC1jb2RlLXJldmlld0BhODU3NzQzYmFiMGUBAg
        MEBQY=
        -----END OPENSSH PRIVATE KEY-----
        
      ssh_host_ed25519_key.pub: |
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIID/fUR3G414nCuk6LQHm89Uq1pXQjD8ac979OM+YyVg gerrit-code-review@a857743bab0e
        
      ssh_host_rsa_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAYEA34ymFGBS8CtW87T453TIyv06ackrB//FeT4/Sdm9qMGiAgAJXZFT
        VHK5/DevcpMMppMWgIzgFH/fIVr6OxzDWEbwPG7CnBtzXLME3HnxAgL2lliTSN2RFTRqw3
        RO0wpHVy42+ahDTO95T1QFq2HA4C1443g9hSX6c/ta8q/gKENAkl4bvtiaX6wtkXUbVAMC
        MfCd6sASNQV9DNg2x8hiAADY5OzccmOjKdVfsSYhFgCvRlZwEEQDUfj6QLK0kg4lTqlBki
        LOduwJHIqa0V8xcRR75wYA/e0wXk2UORhZMDSgendTEdhwZvQhM8Sg8Irg2PEWF9OLBznb
        DlTXQNo2ajYJQ7OPpmzo9SwZlA+jVDGoxqG97IzeNwBeZJmc11ckpvcQFB5MXjH8ULshyH
        Ez765RRQsbfxvR/oVgJlzoL57Cs5pdn+W0w0XmSPzCa7Jub+eCcxdSkvppWdtuofpFWPLq
        vW0ZlbBxXbfTFsG0EUr9cAvS+s1IY9qNjMfAQm19AAAFmErPH8VKzx/FAAAAB3NzaC1yc2
        EAAAGBAN+MphRgUvArVvO0+Od0yMr9OmnJKwf/xXk+P0nZvajBogIACV2RU1Ryufw3r3KT
        DKaTFoCM4BR/3yFa+jscw1hG8Dxuwpwbc1yzBNx58QIC9pZYk0jdkRU0asN0TtMKR1cuNv
        moQ0zveU9UBathwOAteON4PYUl+nP7WvKv4ChDQJJeG77Yml+sLZF1G1QDAjHwnerAEjUF
        fQzYNsfIYgAA2OTs3HJjoynVX7EmIRYAr0ZWcBBEA1H4+kCytJIOJU6pQZIiznbsCRyKmt
        FfMXEUe+cGAP3tMF5NlDkYWTA0oHp3UxHYcGb0ITPEoPCK4NjxFhfTiwc52w5U10DaNmo2
        CUOzj6Zs6PUsGZQPo1QxqMahveyM3jcAXmSZnNdXJKb3EBQeTF4x/FC7IchxM++uUUULG3
        8b0f6FYCZc6C+ewrOaXZ/ltMNF5kj8wmuybm/ngnMXUpL6aVnbbqH6RVjy6r1tGZWwcV23
        0xbBtBFK/XAL0vrNSGPajYzHwEJtfQAAAAMBAAEAAAGBAKQCeq6kZPUTtv2iHqMhiVd0Jf
        EKyGlb+7OSObii6YTwWz4AbN6bCnoAmfczm6MBw9xKOc4ijRw9HKVKLCBGYANaOFL+KAWE
        FkVCiiR/ypRhPCzd22EwPYtDI7k2kcY/2ktZ+rd7/bRqVaQfzvEIDQvsEK9Cvk/7px6EoR
        tAccLYZH1+UfjYzZm3ps77Dgu7EVc2Y4WhWTpRRoev8bDtkQjTlk2OgcXi2AiPJV/Ay7Fq
        2y1NqXYlkBIKCwCAm/40JUfXESlOl4DOj7XWiDI3smlWQs5De7fihtt8kQa8J/2D3qo1KJ
        rZ1aDteP5pr/d8JjJkLmSVzZr+8hS599IVcZfKc+JA4juk2/lQPCAXb1q8E1qtVEa7q3uK
        5mskFhlV07jbxFEE0ZGgady6Au4S4nG7sPXKW6AL64cTSrr1egBh8kiqplCy7skCRKX6aN
        cBfJulW9BkiHug8O3tSUWYHgav78uK0uH2WB1zf0mEYRvi6xKu6LzOaUbYOFPU6RUhOQAA
        AMAlsp3VsT9RiIIzJilOsaKhkPblIMi7KK5x/OWi/+olqkcxDxYI8AnsyM2V7zDbs2Hffx
        7If+Zej5U/+B09ZN5/BbB7ZSF6tmgkBUR/CBGD3P5NBTRpYtGdd9uvowDb/gf0mhnWELgV
        snZuvJVs69RiLwVUp0KbJvjugNawOPUuUDHdWF0MaHz7vdW8s5oPLUxhI2p0+HCIlG6ABX
        VlS/eBrXtOqOOwkEdsh+61mcgpJ7X5n+ZjnkvrnotnPxnru6UAAADBAPNaSLaTdah6+bYO
        kXLOgJTEV0Yh9F/TUGZmeE+MnDZ4IRaAnzp6MthWyR1TAIaWJfcFipsKEJV2okOLPCJ+46
        qtcziolLtJ68oQafroWBjppgOA7hce4H7NdJlrWiMGLIGsAAMdJxBacDPegmBX0PkY089+
        lVY7aHPz8dRi+LLDEeeZu874PSjhcERfPLbh1yPeEXNEIulCsncKjlwL7imLqG1QnBngPP
        2xWVLYEBGT4AP2kS5vTgGlmQ8jxchu0wAAAMEA6yrjxY0Fbpridi3YO7wPCnXAs0ztHLMS
        DwjJlP2b72BH5p8VIC4YnQxP8TPXlopf7lWOkkkGVENse0kmhHrCXpxiI4JN66nM+PPlQ8
        wy+TMr1ww+nAYlYO697rDQnqLqE0zNh9MkJBmc+U6l/Kgzf+qnI9uBxTWUv1vewZI8S8Ih
        dxNunG9Do4tkxt6tC33ddCvRS3hJQBk1eG++tFkrCEU5VBG46Josfw6YtFB9rHGuh/X5kj
        sgCmQ9Gjr9gCBvAAAAH2dlcnJpdC1jb2RlLXJldmlld0BhODU3NzQzYmFiMGUBAgM=
        -----END OPENSSH PRIVATE KEY-----
        
      ssh_host_rsa_key.pub: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDfjKYUYFLwK1bztPjndMjK/TppySsH/8V5Pj9J2b2owaICAAldkVNUcrn8N69ykwymkxaAjOAUf98hWvo7HMNYRvA8bsKcG3NcswTcefECAvaWWJNI3ZEVNGrDdE7TCkdXLjb5qENM73lPVAWrYcDgLXjjeD2FJfpz+1ryr+AoQ0CSXhu+2JpfrC2RdRtUAwIx8J3qwBI1BX0M2DbHyGIAANjk7NxyY6Mp1V+xJiEWAK9GVnAQRANR+PpAsrSSDiVOqUGSIs527AkciprRXzFxFHvnBgD97TBeTZQ5GFkwNKB6d1MR2HBm9CEzxKDwiuDY8RYX04sHOdsOVNdA2jZqNglDs4+mbOj1LBmUD6NUMajGob3sjN43AF5kmZzXVySm9xAUHkxeMfxQuyHIcTPvrlFFCxt/G9H+hWAmXOgvnsKzml2f5bTDReZI/MJrsm5v54JzF1KS+mlZ226h+kVY8uq9bRmVsHFdt9MWwbQRSv1wC9L6zUhj2o2Mx8BCbX0= gerrit-code-review@a857743bab0e
        
storageClasses:
  default:
    name: rook-ceph-block
  shared:
    name: rook-cephfs
