gerrit:
  plugins:
    packaged:
    - "commit-message-length-validator"
    - "download-commands"
    - "replication"
    - "reviewnotes"
    - "webhooks"
    - "gitiles"
    - "hooks"
    - "plugin-manager" 
    - "delete-project"
    - "codemirror-editor"
  service:
    type: "LoadBalancer"
  ingress:
    host: "gerrit.local"
  etc:
    config:
      gitiles.config: |-
        [markdown]
          render = true
      
      project.config: |-
       

      gerrit.config: |-
        [gerrit]
          basePath = git # FIXED
          serverId = 08bdfaeb-f1f9-402c-9496-1aedbbde3b8a
          # The canonical web URL has to be set to the Ingress host, if an Ingress
          # is used. If a LoadBalancer-service is used, this should be set to the
          # LoadBalancer's external IP. This can only be done manually after installing
          # the chart, when you know the external IP the LoadBalancer got from the
          # cluster.
          canonicalWebUrl = http://gerrit.local/
          canonicalGitUrl = git://gerrit.local/
          disableReverseDnsLookup = true
          ui = POLYGERRIT
        [index]
          type = LUCENE
          onlineUpgrade = false # FIXED
        [auth]
          type = LDAP
        [ldap]
          server = ldap://openldap.ldap

          accountBase = ou=people,dc=my-company,dc=com
          accountPattern = (&(objectClass=inetOrgPerson)(uid=${username}))
          accountFullName = cn
          accountEmailAddress = mail

          groupBase = ou=groups,dc=my-company,dc=com
          groupMemberPattern = (&(objectClass=posixGroup)(memberUid=${username}))
        [httpd]
          # If using an ingress use proxy-http or proxy-https
          listenUrl = proxy-http://*:8080/
          requestLog = true
        [sshd]
          listenAddress = off
        [transfer]
          timeout = 120 s
        [user]
          name = Gerrit Code Review
          email = gerrit@my-company.com
          anonymousCoward = Unnamed User
        [cache]
          directory = cache
        [container]
          user = gerrit # FIXED
          javaHome = /usr/lib/jvm/java-1.8-openjdk # FIXED
          javaOptions = -Djavax.net.ssl.trustStore=/var/gerrit/etc/keystore # FIXED
          javaOptions = -Xms200m
          # Has to be lower than 'gerrit.resources.limits.memory'. Also
          # consider memories used by other applications in the container.
          javaOptions = -Xmx4g

    secret:
      secure.config: |-
        [auth]
          registerEmailPrivateKey = m9HMpzcaWiqEUw7U+qE8y4iTG01CU3CspfY=
        [database]
          username = postgres
          password = Askiv4ViRfCUdiwT
        [ldap]
          username = cn=admin,dc=my-company,dc=com
          password = secret
          # Password for the keystore added as value for 'gerritReplica.keystore'
          # Only needed, if SSL is enabled.
          #[httpd]
          #  sslKeyPassword = gerrit

          # Credentials for replication targets
          # [remote "replica"]
          # username = git
          # password = secret

storageClasses:
  default:
    name: rook-ceph-block
  shared:
    name: rook-cephfs