---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    component: jenkins
    app: jenkins
  ports:
    - port: 8080
      nodePort: 31900
      name: "http"
    - port: 50000
      nodePort: 31901
      name: "jnlp"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-statefulset
  labels:
    app: jenkins
spec:
  serviceName: jenkins-service
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        component: jenkins
    spec:
      containers:
        # https://hub.docker.com/r/jenkins/jenkins
        - name: jenkins-container
          image: jenkins/jenkins:2.239-centos
          volumeMounts:
            - name: jenkins-home-persistentvolumeclaim
              mountPath: /var/jenkins_home
  volumeClaimTemplates:
    - metadata:
        name: jenkins-home-persistentvolumeclaim
        labels:
          app: jenkins
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
