apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  ventheAppIdentifier: ghost

namespace: ghost-namespace

images:
  - name: ghost
    newTag: 3.33.0

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: ghost-service
  path: ghost-service-patch.yaml

resources:
  - manifests/namespace.yaml
  - manifests/ghost.yaml
