apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  labels:
    app: ldap
spec:
  selector:
    component: ldap
    app: ldap
  ports:
    - port: 389
      targetPort: 389
      name: ldap
    - port: 636
      targetPort: 636
      name: ldaps

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldap-statefulset
  labels:
    app: ldap
spec:
  serviceName: ldap-service
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
        component: ldap
    spec:
      containers:
        - name: ldap-container
          ports:
            - containerPort: 389
              protocol: TCP
            - containerPort: 636
              protocol: TCP
          # https://github.com/osixia/docker-openldap
          image: osixia/openldap:1.3.0
          env:
            - name: LDAP_ADMIN_PASSWORD
              value: "secret"
            - name: LDAP_ORGANISATION
              value: "My Company"
            - name: LDAP_DOMAIN
              value: "my-company.com"
            - name: LDAP_TLS
              value: "false"
          volumeMounts:
            - name: var-lib-ldap-persistentvolumeclaim
              mountPath: /var/lib/ldap
            - name: etc-ldap-slapd-d-persistentvolumeclaim
              mountPath: /etc/ldap/slapd.d
  volumeClaimTemplates:
    - metadata:
        name: openldap-var-lib-ldap-persistentvolumeclaim
        labels:
          app: ldap
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
    - metadata:
        name: openldap-etc-ldap-slapd-d-persistentvolumeclaim
        labels:
          app: ldap
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
