apiVersion: v1
kind: Service
metadata:
  name: ldapadmin-service
  labels:
    app: ldapadmin
spec:
  type: NodePort
  selector:
    component: ldapadmin
    app: ldapadmin
  ports:
    - port: 80
      nodePort: 30300
      name: http
    - port: 443
      nodePort: 30301
      name: https

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldapadmin-deployment
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldapadmin
  template:
    metadata:
      labels:
        app: ldapadmin
        component: ldapadmin
    spec:
      containers:
        - name: ldapadmin-container
          image: osixia/phpldapadmin:0.9.0
          ports:
            - containerPort: 443
            - containerPort: 80
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "ldap"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"