#file: noinspection YAMLSchemaValidation
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: kustomized-helm
spec:
  init:
    command: ["bash"]
    args: ["-c", "manager init"]
  generate:
    command: ["bash"]
    args: ["-c", "manager generate"]
  parameters:
    static:
      - name: helmChart
        title: Name of the chart
        required: true
      - name: helmReleaseName
        title: Release name for the chart
        required: true
      - name: additionalManifests
        collectionType: array
      - name: patches
        collectionType: map
      - name: values
        collectionType: map
