apiVersion: v1
kind: Service
metadata:
  name: xwiki-database-service
  labels:
    app: xwiki
spec:
  type: NodePort
  selector:
    app: xwiki
    component: xwiki-database
  ports:
    - port: 3306
      nodePort: 31252
      name: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xwiki-database-statefulset
  labels:
    app: xwiki
spec:
  serviceName: xwiki-database-service
  replicas: 1
  selector:
    matchLabels:
      app: xwiki
  template:
    metadata:
      labels:
        app: xwiki
        component: xwiki-database
    spec:
      # https://hub.docker.com/_/mariadb
      containers:
        - name: xwiki-database-container
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: xwiki-secret
                  key: DB_USER
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: xwiki-secret
                  key: DB_USER
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xwiki-secret
                  key: DB_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xwiki-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              value: xwiki-database
          ports:
            - containerPort: 3306
              protocol: TCP
          image: mariadb:10.5.3
          volumeMounts:
            - name: xwiki-database-data-persistentvolumeclaim
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: xwiki-database-data-persistentvolumeclaim
        labels:
          app: xwiki
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 512Mi
---