---
kind: Service
apiVersion: v1
metadata:
  name: xwiki-service
  labels:
    app: xwiki
spec:
  type: NodePort
  selector:
    component: xwiki
  ports:
    - port: 8080
      nodePort: 31253
      name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xwiki-statefulset
  labels:
    app: xwiki
spec:
  serviceName: xwiki-service
  replicas: 1
  selector:
    matchLabels:
      app: xwiki
  template:
    metadata:
      labels:
        app: xwiki
        component: xwiki
    spec:
      containers:
        # https://hub.docker.com/_/xwiki
        - name: xwiki-container
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: xwiki-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xwiki-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              value: xwiki-database
          image: xwiki:12.4
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: xwiki-data-persistentvolumeclaim
              mountPath: /usr/local/xwiki
  volumeClaimTemplates:
    - metadata:
        name: xwiki-data-persistentvolumeclaim
        labels:
          app: xwiki
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
---

