apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xwiki-namespace

commonLabels:
  ventheAppIdentifier: xwiki

secretGenerator:
  - name: xwiki-secret
    type: Opaque
    env: secrets/database-secret.txt

images:
  - name: xwiki
    newTag: 12.7.1-mysql-tomcat
  - name: mariadb
    newTag: "10.5.3"

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: xwiki-service
  path: xwiki-service-patch.yaml

resources:
  - manifests/namespace.yaml
  - manifests/database.yaml
  - manifests/xwiki.yaml
