- name: Set Kubernetes DNS
  become: true
  ansible.builtin.blockinfile:
    create: true
    dest: /etc/systemd/resolved.conf.d/kubernetes-dns.conf
    block: |
      [Resolve]
      DNSSEC=false
      DNS={{ dns_ip }}
      FallbackDNS=8.8.8.8 1.1.1.1
  notify:
    - "Restart SystemD services"
- name: Login to gerrit
  ansible.builtin.debug:
    msg: |
      You can check the status with `resolvectl status` or
      sudo systemctl status systemd-resolved.service
