ingress:
  enabled: true
  additionalAnnotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: ca-issuer
  host: "{{gerrit.release_name}}.{{ tld_hostname }}"
  tls:
    enabled: true
    secret:
      create: false
      name: "{{gerrit.release_name}}-tls"

gerrit:
  plugins:
    packaged:
    - "commit-message-length-validator"
    - "download-commands"
    - "replication"
    - "reviewnotes"
    - "webhooks"
    - "gitiles"
    - "hooks"
    - "plugin-manager"
    - "delete-project"
    - "codemirror-editor"
  service:
    type: LoadBalancer
    ssh:
      enabled: true
      port: 29418
  etc:
    config:
      gitiles.config: |
        {% filter indent(width=8,blank=True) %}{% include './files/gitiles.config.j2' %}{% endfilter %}

      project.config: |
        {% filter indent(width=8,blank=True) %}{% include './files/project.config.j2' %}{% endfilter %}

      gerrit.config: |
        {% filter indent(width=8,blank=True) %}{% include './files/gerrit.config.j2' %}{% endfilter %}

    secret:
      secure.config: |
        {% filter indent(width=8,blank=True) %}{% include './files/secure.config.j2' %}{% endfilter %}

      ssh_host_ecdsa_384_key: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_ecdsa_384_key' %}{% endfilter %}

      ssh_host_ecdsa_384_key.pub: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_ecdsa_384_key.pub' %}{% endfilter %}

      ssh_host_ecdsa_521_key: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_ecdsa_521_key' %}{% endfilter %}

      ssh_host_ecdsa_521_key.pub: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_ecdsa_521_key.pub' %}{% endfilter %}

      ssh_host_ecdsa_key: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_ecdsa_key' %}{% endfilter %}

      ssh_host_ecdsa_key.pub: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_ecdsa_key.pub' %}{% endfilter %}

      ssh_host_ed25519_key: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_ed25519_key' %}{% endfilter %}

      ssh_host_ed25519_key.pub: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_ed25519_key.pub' %}{% endfilter %}

      ssh_host_rsa_key: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_rsa_key' %}{% endfilter %}

      ssh_host_rsa_key.pub: |
        {% filter indent(width=8,blank=True) %}{% include './files/ssh_host_rsa_key.pub' %}{% endfilter %}

storageClasses:
 default:
   name: "{{ storageClass }}"
 shared:
   name: "{{ storageClass }}"
