---
- name: Disable swap
  gather_facts: true
  become: true
  hosts: all
  tasks:
    # Swap has to be disabled for Kubernetes
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
    - name: Disable swap
      command: swapoff --all
      when: ansible_swaptotal_mb > 0
    - name: Create swapoff service
      copy:
        mode: '0644'
        owner: 'root'
        dest: "/lib/systemd/system/swapoff.service"
        content: |
          [Unit]
          Description=Swap off

          [Service]
          ExecStart=/sbin/swapoff --all

          [Install]
          WantedBy=multi-user.target
    - name: Enable swapoff service
      service:
        name: swapoff
        state: started
- name: Prepare for elasticsearch containers
  gather_facts: true
  become: true
  hosts: all
  tasks:
    - name: Set "vm.max_map_count" for Elasticsearch
      ansible.posix.sysctl:
        name: "vm.max_map_count"
        value: "262144"
        state: present
        sysctl_set: true
        reload: true
...
