version: "3.7"

services:

  # https://hub.docker.com/r/portainer/portainer
  portainer:
    container_name: "portainer"
    image: portainer/portainer:1.22.1
    ports:
      # UI/Portainer API/Polling
      - "13001:9000"
      # SSH tunnel server used to create a secure tunnel between the agent and the Portainer instance.
      # - "8000:8000"
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #   - portainer_data:/data

  # https://hub.docker.com/r/openzipkin/zipkin
  # zipkin:
  #   container_name: zipkin
  #   image: openzipkin/zipkin:2.19.1

  # https://hub.docker.com/r/grafana/grafana
  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:6.4.3

  # https://hub.docker.com/_/logstash
  # logstash:
  #   container_name: logstash
  #   image: logstash:7.4.2

  # https://hub.docker.com/_/elasticsearch
  # elasticsearch:
  #   container_name: elasticsearch
  #   image: elasticsearch:7.4.2

  # https://hub.docker.com/_/kibana
  # kibana:
  #   container_name: kibana
  #   image: kibana:7.4.2


# volumes:
#   portainer_data:

networks:
  default:
    name: monitoring
  external:
    name: internal