- name: Clean previous SSH keys
  ansible.builtin.shell:
    curl \
      https://gerrit.home.arpa/a/accounts/self/sshkeys \
      --user {{jenkins.user}}:{{jenkins.password}} \
      --fail \
      --show-error \
      --silent \
    | sed "s/)]}'//g" \
    | jq '.[].seq' \
    | xargs -I{} \
      curl \
        --request DELETE https://gerrit.home.arpa/a/accounts/self/sshkeys/{} \
        --user {{jenkins.user}}:{{jenkins.password}} \
        --fail \
        --show-error \
        --silent
- name: Register SSH key on Gerrit
  ansible.builtin.shell: |
    curl \
      --request POST https://{{ gerrit.url }}/a/accounts/self/sshkeys \
      --data "{{sshkey_pub.stdout}}" \
      --user {{jenkins.user}}:{{jenkins.password}} \
      --header 'Content-Type: text/plain' \
      --fail \
      --show-error \
      --silent
