- name: Set up Helm repository
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: https://charts.jenkins.io
- name: Install Jenkins
  kubernetes.core.helm:
    chart_version: "4.3.0"
    create_namespace: true
    update_repo_cache: true
    name: "{{ jenkins.release_name }}"
    chart_ref: jenkins/jenkins
    release_namespace: "{{ jenkins.namespace }}"
    values: "{{ lookup('template', './values.yml') | from_yaml }}"
