- name: Creates directory
  become: "true"
  file:
    path: "/var/lib/containerd/io.containerd.snapshotter.v1.zfs/"
    state: directory
- name: Create a zvol for snapshots
  become: "true"
  community.general.zfs:
    #-snapshots
    name: "main/containerd"
    state: present
    extra_zfs_properties:
      mountpoint: /var/lib/containerd/io.containerd.snapshotter.v1.zfs
- name: Set containerd configuration
  become: true
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*snapshotter)\s*=\s*.*$'
    line: '\1 = "zfs"'
    backrefs: yes
- name: Restart containerd
  become: true
  ansible.builtin.service:
    enabled: true
    name: containerd
    daemon_reload: true
    state: restarted
