- ansible.builtin.tempfile:
    state: directory
    suffix: certs
  register: tempdir
- ansible.builtin.git:
    repo: https://github.com/GerritCodeReview/k8s-gerrit.git
    dest: "{{tempdir.path}}"
- kubernetes.core.helm:
    create_namespace: true
    name: "{{gerrit.release_name}}"
    chart_ref: "{{tempdir.path}}/helm-charts/gerrit"
    release_namespace: "{{ gerrit.namespace }}"
    values: "{{ lookup('template', './gerrit-values.yml') | from_yaml }}"
- kubernetes.core.k8s:
    state: patched
    name: gerrit-gerrit-ingress
    namespace: gerrit
    kind: Ingress
    definition:
      spec:
        rules:
          #- host: ssh.gerrit.home.arpa
          #  http:
          #    paths:
          #    - backend:
          #        service:
          #          name: gerrit-gerrit-service
          #          port:
          #            number: 29418
          #      path: /
          #      pathType: ImplementationSpecific
          - host: gerrit.home.arpa
            http:
              paths:
                - backend:
                    service:
                      name: gerrit-gerrit-service
                      port:
                        number: 80
                  path: /
                  pathType: Prefix
        tls:
          - hosts:
              - gerrit.home.arpa
            #- ssh.gerrit.home.arpa
            secretName: gerrit-tls
- name: Annotate service with external hostname
  command: |
    kubectl annotate Service {{gerrit.release_name}}-gerrit-service \
      --namespace={{ gerrit.namespace }} \
      --overwrite external-dns.alpha.kubernetes.io/hostname="ssh.{{gerrit.release_name}}.{{tld_hostname}}"
- ansible.builtin.file:
    path: "{{ tempdir.path }}"
    state: absent
  when: tempdir.path is defined
- name: Login to gerrit
  ansible.builtin.pause:
    prompt: |
      Make sure to login as admin to gerrit.home.arpa!
      Gerrit will set the first logged in user as administrator
