kind: Service
apiVersion: v1
metadata:
  name: plantuml-service
  labels:
    app: plantuml
spec:
  type: LoadBalancer
  selector:
    component: plantuml-pod
  ports:
    - port: 80
      targetPort: 8080
      name: "http"
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: plantuml-deployment
  labels:
    app: plantuml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml
  template:
    metadata:
      labels:
        app: plantuml
        component: plantuml-pod
    spec:
      containers:
        - name: plantuml-pod
          # https://hub.docker.com/r/plantuml/plantuml-server
          image: plantuml/plantuml-server:jetty-v1.2020.17