---
- name: Deploy LDAP
  gather_facts: false
  hosts: all
  vars:
    TEMP_DIRECTORY: "/tmp/cert-manager"
  vars_prompt:
    - name: should_clean
      prompt: Should clean before install
      default: false
      private: no
    - name: namespace
      prompt: Namespace
      default: "cert-manager"
      private: no
    - name: release_name
      prompt: Release name
      default: "cert-manager"
      private: no
    - name: chown_user
      default: vagrant
  tasks:
    - name: Delete old releases
      command: "helm uninstall --namespace={{ namespace }} {{ release_name }}"
      when: "should_clean|bool"
    - name: Delete namespace
      command: "kubectl delete namespace {{ namespace }}"
      when: "should_clean|bool"
    - name: Create temporary directories
      become: true
      file:
        path: "{{ TEMP_DIRECTORY }}"
        state: directory
    - name: Copy manifests
      become: true
      copy:
        src: ./manifests/
        dest: "{{TEMP_DIRECTORY}}"
        directory_mode: yes
        mode: 0777
        owner: "{{ chown_user }}"
    - name: Add helm repository
      command: helm repo add jetstack https://charts.jetstack.io
    - name: Update helm repository
      command: helm repo update
    - name: Deploy helm charts
      shell:
        cmd: |
          helm upgrade --install \
            --namespace={{ namespace }} --create-namespace \
            --values={{TEMP_DIRECTORY}}/values.yml \
            {{ release_name }} \
            jetstack/cert-manager
    - name: Clean temp path
      become: true
      file:
        state: absent
        path: "{{ TEMP_DIRECTORY }}"
