---
- name: Deploy Gerrit
  gather_facts: false
  hosts: all
  vars:
    HTTPD_LISTEN_URL: "proxy-https://*:8080/"
    TEMP_DIRECTORY: "/tmp/gerrit"
    LDAP_SERVER: "ldap://openldap.ldap"
    LDAP_DC: "dc=home,dc=arpa"
  vars_prompt:
    - name: should_clean
      prompt: Should clean before install
      default: false
      private: no
    - name: deployment_namespace
      prompt: Namespace
      default: "gerrit"
      private: no
    - name: chown_user
      default: "ansible"
      private: no
    - name: release_name
      prompt: Release name
      default: "gerrit"
      private: no
    - name: domain
      default: "home.arpa"
      prompt: Domain
      private: no
    - name: storage_class
      default: "zfs-local-dataset"
  tasks:
    - name: Delete old releases
      command: "helm uninstall --namespace={{ deployment_namespace }} {{ release_name }}"
      when: "should_clean|bool"
    - name: Delete namespace
      command: "kubectl delete namespace {{ deployment_namespace }}"
      when: "should_clean|bool"
    - name: Create temporary directories
      become: true
      file:
        path: "{{ TEMP_DIRECTORY }}"
        state: directory
    - name: Templating pass
      become: true
      template:
        src: "./{{ item.input }}"
        dest: "{{ TEMP_DIRECTORY }}/{{ item.output }}"
        owner: "{{ chown_user }}"
        mode: '0777'
      with_items:
        - input: values.yaml.j2
          output: values.yaml
        - input: ingress.yml.j2
          output: ingress.yaml
    # - name: Add helm repository
      # command: helm repo add venthe https://raw.githubusercontent.com/Venthe/k8s-gerrit/various-updates/chart-repository/
    - name: Update helm repositories
      command: helm repo update
    - name: clone
      become: true
      shell:
        cmd: git clone https://github.com/GerritCodeReview/k8s-gerrit.git {{TEMP_DIRECTORY}}/k8s-gerrit
    - name: Deploy helm charts
      shell:
        cmd: |
          helm upgrade --install \
            --namespace={{ deployment_namespace }} --create-namespace \
            --values={{TEMP_DIRECTORY}}/values.yaml \
            {{ release_name }} \
            {{TEMP_DIRECTORY}}/k8s-gerrit/helm-charts/gerrit
    - name: Annotate service with external hostname
      command: |
        kubectl annotate Service {{release_name}}-gerrit-service \
          --namespace={{ deployment_namespace }} \
          --overwrite external-dns.alpha.kubernetes.io/hostname="ssh.{{release_name}}.{{domain}}"
    - name: Add ingress
      command: |
        kubectl apply -f {{TEMP_DIRECTORY}}/ingress.yaml
    - name: Clean temp path
      become: true
      file:
        state: absent
        path: "{{ TEMP_DIRECTORY }}"
