image:
  repository: coredns/coredns
  tag: "1.8.0"
serviceType: "ClusterIP"
replicaCount: 2
serviceAccount:
  create: true
rbac:
  pspEnable: true
isClusterService: false
extraSecrets:
  - name: cilium-etcd-client-tls
    mountPath: /etc/coredns/tls/etcd
servers:
  - zones:
      - zone: .
    port: 53
    plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
      - name: etcd
        parameters: {{ tld_hostname }}
        configBlock: |-
          stubzones
          path /skydns
          endpoint https://cilium-etcd-client.{{ deployment_namespace }}.svc:2379
          tls /etc/coredns/tls/etcd/etcd-client.crt /etc/coredns/tls/etcd/etcd-client.key /etc/coredns/tls/etcd/etcd-client-ca.crt
