apiVersion: v1
kind: Service
metadata:
  name: gerrit-database-service
  labels:
    app: gerrit
spec:
  type: NodePort
  selector:
    app: gerrit
    component: gerrit-database
  ports:
    - port: 5432
      nodePort: 32202
      name: pgsql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gerrit-database-statefulset
  labels:
    app: gerrit
spec:
  serviceName: gerrit-database-service
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
  template:
    metadata:
      labels:
        app: gerrit
        component: gerrit-database
    spec:
      containers:
        # https://hub.docker.com/_/postgres
        - name: gerrit-database-container
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: "reviewdb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gerrit-secret
                  key: postgresql_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gerrit-secret
                  key: postgresql_password
          volumeMounts:
            - name: gerrit-database-data-persistentvolumeclaim
              mountPath: /var/lib/postgresql/data
            - name: gerrit-database-init-persistentvolumeclaim
              mountPath: /docker-entrypoint-initdb.d
  volumeClaimTemplates:
    - metadata:
        name: gerrit-database-data-persistentvolumeclaim
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "512Mi"
    - metadata:
        name: gerrit-database-init-persistentvolumeclaim
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "16Mi"
