kind: Service
apiVersion: v1
metadata:
  name: gerrit-service
  labels:
    app: gerrit
spec:
  type: NodePort
  selector:
    component: gerrit
    app: gerrit
  ports:
    - port: 8080
      nodePort: 32200
      name: "http"
    - port: 29418
      nodePort: 32201
      name: "git"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gerrit-statefulset
  labels:
    app: gerrit
spec:
  serviceName: gerrit-service
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
  template:
    metadata:
      labels:
        app: gerrit
        component: gerrit
    spec:
      volumes:
        - name: gerrit-tmp-volume
          emptyDir:
            medium: Memory
        - name: gerrit-init-volume
          configMap:
            name: gerrit-configmap
      initContainers:
        # FIXME: FIX-004 Add waiting for host being present
        - name: gerrit-copy-configs-initcontainer
          # https://hub.docker.com/r/gerritcodereview/gerrit
          image: gerritcodereview/gerrit:3.2.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          envFrom:
            - secretRef:
                name: gerrit-secret
          volumeMounts:
            - name: gerrit-init-volume
              mountPath: /var/k8s/init
          command: ["sh", "-c"]
          args:
            - cp /var/k8s/init/* /var/gerrit/etc;
              cd /var/gerrit/etc;
              sed -i '/username = / s/= .*/= $postgresql_username/g' gerrit.config;
              sed -i '/password = / s/= .*/= $postgresql_password/g' gerrit.config;
      # FIXME: FIX-006 Add init to gerrit
      # FIXME: FIX-005 Add reindex to gerrit
      containers:
        - name: gerrit-container
          image: gerritcodereview/gerrit:3.2.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          envFrom:
            - secretRef:
                name: gerrit-secret
          volumeMounts:
            - name: gerrit-git-persistentvolumeclaim
              mountPath: /var/gerrit/git
            - name: gerrit-index-persistentvolumeclaim
              mountPath: /var/gerrit/index
            - name: gerrit-cache-persistentvolumeclaim
              mountPath: /var/gerrit/cache
            - name: gerrit-etc-persistentvolumeclaim
              mountPath: /var/gerrit/etc
            - name: gerrit-tmp-volume
              mountPath: /var/gerrit/tmp
  volumeClaimTemplates:
    - metadata:
        name: gerrit-git-persistentvolumeclaim
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: gerrit-index-persistentvolumeclaim
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
    - metadata:
        name: gerrit-cache-persistentvolumeclaim
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 64Mi
    - metadata:
        name: gerrit-etc-persistentvolumeclaim
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 64Mi
