apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  ventheAppIdentifier: gerrit

namespace: gerrit-namespace

secretGenerator:
  - name: gerrit-secret
    type: Opaque
    env: secrets/database.txt
    files:
      - secrets/secure.config
      - secrets/ssh_host_rsa_key
      - secrets/ssh_host_rsa_key.pub

configMapGenerator:
  - name: gerrit-configmap
    files:
      - configMaps/gerrit.config

images:
  - name: gerritcodereview/gerrit
    newTag: 3.2.3

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: gerrit-service
  path: gerrit-service-patch.yaml

resources:
  - manifests/namespace.yaml
  - manifests/database.yaml
  - manifests/gerrit.yaml
