---
- name: Deploy LDAP
  gather_facts: false
  hosts: all
  vars:
    TEMP_DIRECTORY: "/tmp/nexus"
  vars_prompt:
    - name: should_clean
      prompt: Should clean before install
      default: false
      private: no
    - name: namespace
      prompt: Namespace
      default: "nexus"
      private: no
    - name: release_name
      prompt: Release name
      default: "nexus"
      private: no
    - name: nexus_version
      default: "38.0.0"
    - name: domain_name
      default: "home.arpa"
      prompt: Domain
      private: no
    - name: chown_user
      default: "vagrant"
      private: no
  tasks:
    - name: Delete old releases
      command: "helm uninstall --namespace={{ namespace }} {{ release_name }}"
      when: "should_clean|bool"
    - name: Delete namespace
      command: "kubectl delete namespace {{ namespace }}"
      when: "should_clean|bool"
    - name: Create temporary directories
      become: true
      file:
        path: "{{ TEMP_DIRECTORY }}"
        state: directory
    - name: Templating pass
      become: true
      template:
        src: "./templates/{{item}}.j2"
        dest: "{{ TEMP_DIRECTORY }}/{{item}}"
        owner: "{{ chown_user }}"
        mode: '0777'
      with_items:
        - values.yml
    - name: Add helm repository
      command: helm repo add sonatype https://sonatype.github.io/helm3-charts/
    - name: Update helm repository
      command: helm repo update
    - name: Deploy helm charts
      shell:
        cmd: |
          helm upgrade --install \
            --create-namespace --namespace={{ namespace }} \
            --version {{ nexus_version }} \
            --values={{ TEMP_DIRECTORY }}/values.yml \
            {{ release_name }} \
            sonatype/nexus-repository-manager
    - name: Clean temp path
      become: true
      file:
        state: absent
        path: "{{ TEMP_DIRECTORY }}"
