---
# Run on every node
  - name: Update CRI
  gather_facts: false
  hosts: all
  vars_prompt:
    - name: chown_user
      default: vagrant
      private: false
  vars:
    docker_proxy_protocol: http
    docker_proxy: localhost:31201
    docker_private_protocol: http
    docker_private: localhost:31200
  tasks:
    - name: Update containerd with mirrors
      blockinfile:
        dest: /etc/containerd/config.toml
        block: |
          [plugins]
            [plugins.cri]
              [plugins.cri.registry]
                [plugins.cri.registry.mirrors]
                  [plugins.cri.registry.mirrors."docker.io"]
                    endpoint = ["{{docker_proxy_protocol}}/{{docker_proxy}}"]
                  [plugins.cri.registry.mirrors."{{docker_private}}"]
                    endpoint = ["{{docker_private_protocol}}/{{docker_private}}"]
        owner: '{{ chown_user }}'
      become: true
      notify: Restart containerd

  handlers:
    - name: Restart containerd
      become: true
      service:
        name: containerd
        state: restarted
