ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: ca-issuer
  host: kafka-ui.home.arpa
  tls:
    enabled: true
    secretName: "test-deployment-tls"
yamlApplicationConfig:
   kafka:
     clusters:
       - name: yaml
         bootstrapServers: kafka:9092
   auth:
     type: disabled
   management:
     health:
       ldap:
         enabled: false