version: "3.7"

services:

  # https://hub.docker.com/r/osixia/openldap
  ldap:
    image: osixia/openldap:1.3.0
    container_name: ldap
    hostname: ldap
    environment:
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_ORGANISATION=My Company
      - LDAP_DOMAIN=my-company.com
      - LDAP_TLS=false
    command: --loglevel debug
    expose:
      # LDAP
      - "389"
      # LDAP over SSL
      - "636"
    ports:
      # LDAP
      - "12389:389"
      # LDAP over SSL
      - "12636:636"
    # volumes:
      # - /ldap/var:/var/lib/ldap
      # - /ldap/etc:/etc/ldap/slapd.d

  # https://hub.docker.com/r/osixia/phpldapadmin
  ldap_admin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap-admin
    ports:
      # HTTP access
      - "12080:80"
      # HTTPS access
      - "12443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - ldap

networks:
  default:
    name: ldap
  external:
    name: internal
