---
apiVersion: v1
kind: Secret
metadata:
  name: gerrit-secret
  labels:
    app: gerrit
data:
  postgresql_username: cG9zdGdyZXM=
  postgresql_password: QXNraXY0VmlSZkNVZGl3VA==
---
kind: Service
apiVersion: v1
metadata:
  name: gerrit
  labels:
    app: gerrit
spec:
  type: NodePort
  selector:
    component: "gerrit"
  ports:
    - port: 8080
      nodePort: 32200
      name: "web"
    - port: 29418
      nodePort: 32201
      name: "backend"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gerrit
  labels:
    app: gerrit
spec:
  serviceName: "gerrit"
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
  template:
    metadata:
      labels:
        app: gerrit
        component: gerrit
    spec:
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
        - name: init
          configMap:
            name: gerrit-etc
      initContainers:
        # FIXME: FIX-004 Add waiting for host being present
        - name: copy-configs
          image: gerritcodereview/gerrit:3.1.3
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          envFrom:
            - secretRef:
                name: gerrit-secret
          volumeMounts:
            - name: init
              mountPath: /var/k8s/init
          command: ["sh", "-c"]
          args:
            - cp /var/k8s/init/* /var/gerrit/etc;
              cd /var/gerrit/etc;
              sed -i '/username = / s/= .*/= $postgresql_username/g' gerrit.config;
              sed -i '/password = / s/= .*/= $postgresql_password/g' gerrit.config;
      # FIXME: FIX-006 Add init to gerrit
      # FIXME: FIX-005 Add reindex to gerrit
      containers:
        - name: gerrit-container
          image: gerritcodereview/gerrit:3.1.3
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          envFrom:
            - secretRef:
                name: gerrit-secret
          volumeMounts:
            - name: git
              mountPath: /var/gerrit/git
            - name: index
              mountPath: /var/gerrit/index
            - name: cache
              mountPath: /var/gerrit/cache
            - name: etc
              mountPath: /var/gerrit/etc
            - name: tmp
              mountPath: /var/gerrit/tmp
  volumeClaimTemplates:
    - metadata:
        name: git
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: index
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
    - metadata:
        name: cache
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 64Mi
    - metadata:
        name: etc
        labels:
          app: gerrit
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 64Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gerrit-etc
  labels:
    app: gerrit
data:
  gerrit.config: |
    [gerrit]
      basePath = git
      serverId = 08bdfaeb-f1f9-402c-9496-1aedbbde3b8a
      canonicalWebUrl = http://kubernetes.docker.internal:32200/
      ui = POLYGERRIT
    [database]
      type = POSTGRESQL
      hostname = gerrit-reviewdatabase
      port = 5432
      database = reviewdb
      username = gerrit2
      password = password
    [index]
      type = LUCENE
    [auth]
      type = DEVELOPMENT_BECOME_ANY_ACCOUNT
    [receive]
      enableSignedPush = false
    [sendemail]
      smtpServer = localhost
    [container]
      user = gerrit
      javaHome = /usr/lib/jvm/jre-openjdk
    [sshd]
      listenAddress = *:29418
    [httpd]
      listenUrl = http://*:8080/
    [cache]
      directory = cache
  secure.config: |
    [auth]
      registerEmailPrivateKey = m9HMpzcaWiqEUw7U+qE8y4iTG01CU3CspfY=
  # Replace with your own generated key pair. See: ssh-keygen
  ssh_host_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAuez8q38u3eInE7SkTeti6Fu88bkOUoPqhKq8z1K3J+gPgniS
    +NfeHLniZamvyhABbgmO/f4mr/H3x/krh1uoh+AY05JUMNNW5FlzsPSYS6YcLSQB
    OOFMHcgyPU8+7ajFYcArWs0Maf7IxOCplPkrKLUMK4BO4ydU60Xm0N/aj8nub8CT
    FAtYZCk3jl4MIlEWDEqDDVWSKeCq546NMlOfxSpVrDWqSShULFY9WWdUVqfjzEBu
    qYGmQqm0SZqU0fYK189t8dvSAjej/DKTmp6B1UHogWk2oZOs95QzYXp/ViScYcSq
    JZcDuK4BlSV7vviTUOfLzR9z9YnIADU+bZcWlQIDAQABAoIBAQCh4qYSEPhWu/44
    WzYgnk6NcKswcWf2EuRUxXEGt8fAGH/Ao4mc4CCGNJfa2wez0YHdNLdrkipPUkjj
    tqHfBsDUJhyXwzZJGQr0YqqoLiCY5bZs24ew5gJngBO2bFSnjCbouPFG63jepbhc
    LB2cF+QrWpCRI/QMNwfqnv+daPwd60A3c1LzZuSvEpZ9/I1m7sVdN6h5lPJZ/nEg
    gnY9hCTiak3ujMmGuVONt+jX+kF3wAM7D6Yd7cGtphLXr6NqXb7L6cXVteabXAG1
    mM3GytH+PgzbLNPXFBELDwyC7lXTAiP2yaX/uXo1o0RO2wPwK0GgIgCO94nvd0sE
    nyhh0RzVAoGBAPFAUnrZHlajdZaScLs/RmbgYtHrXMXNOIcXcJ42YK9K6WfYOHzT
    E02NvIiTbg1hImbFwa3hKnuAlNRuXwIfchRkqfYdvRPw1pYvpwhSZONWGXZkmzme
    m1YcNnQBc7e9HNtijFZAf3g+MQln4tJOe17NJwjazaujnqiT0TsUBIVDAoGBAMVK
    zGF6jiYWUiczpEzY2SCqSsk5D5D/+K1G5tfgIL4Mo8cl6yIqwiG+ShKE2JsuBhr2
    0zuzBJAnrJo0IWZRslK0+/rtvgtB6c79D9HvB+c7eTPgwwc+xcBmewNvtzUzRduB
    s0+POiSrrGl3z9B1zMm56tk9LUqnswrODS5rDstHAoGALm02cjW+ROYIBwX/c8ll
    fv7HhaZJoDcyHa1BGvFUAefkqvtNQ5hLKq2QDqhwkVqUCDseXpvqVQIVohvrZLkw
    dwQ4QQjQDjpW0WgyOMPCbo1vMP2Dcb84HYYoZIKzBjT6jK2WXDLlVPqC7VB0sgww
    aboJPQb+dX1zVvW7WicsB4kCgYEAmiZ1RnzBcFTkX6jj6P9Nt04XHN4uoXa+0HSj
    jWybaKLrnICuFYYfJMpPieSucaEmOA8+wFiBajj1jY7Jwe53TFQIxejYImefzZDA
    uaDwJeW8L6Kf/5s2W7w2xVqWZUTogjf26GTaYyiXj9iDUTeZiMxxCMfaCYi6Rej1
    N52Cc6UCgYBQKdDe0gFPjW97CyPPDQVcxAIeAVveFmWRM+uA2UVIMgb9nSZp+YnL
    /miUmk3fdGODediw5YaAuP0Z7U0/HwBg/aGyZNNyjMQd2BIDxCFCHJoipR1RP812
    /taHdSomlc1aM85O9G6kFPhTEPMSw3x/lSK0wmb5ipKwUR7jKthkOQ==
    -----END RSA PRIVATE KEY-----
  ssh_host_rsa_key.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC57Pyrfy7d4icTtKRN62LoW7zxuQ5Sg+qEqrzPUrcn6A+CeJL4194cueJlqa/KEAFuCY79/iav8ffH+SuHW6iH4BjTklQw01bkWXOw9JhLphwtJAE44UwdyDI9Tz7tqMVhwCtazQxp/sjE4KmU+SsotQwrgE7jJ1TrRebQ39qPye5vwJMUC1hkKTeOXgwiURYMSoMNVZIp4Krnjo0yU5/FKlWsNapJKFQsVj1ZZ1RWp+PMQG6pgaZCqbRJmpTR9grXz23x29ICN6P8MpOanoHVQeiBaTahk6z3lDNhen9WJJxhxKollwO4rgGVJXu++JNQ58vNH3P1icgANT5tlxaV gerrit-code-review@08c96057f196
---
apiVersion: v1
kind: Service
metadata:
  name: gerrit-reviewdatabase
  labels:
    app: gerrit
spec:
  type: NodePort
  selector:
    component: reviewdatabase
  ports:
  - port: 5432
    nodePort: 32202
    name: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gerrit-reviewdatabase
  labels:
    app: gerrit
spec:
  serviceName: gerrit-reviewdatabase
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
  template:
    metadata:
      labels:
        app: gerrit
        component: reviewdatabase
    spec:
      volumes:
        # FIXME: FIX-002 Add persistent volume over linux
        #  Postgres does not support windows volumes
        - name: data
          emptyDir:
            medium: Memory
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        env:
          - name: POSTGRES_DB
            value: "reviewdb"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: gerrit-secret
                key: postgresql_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gerrit-secret
                key: postgresql_password
        volumeMounts:
         - name: data
           mountPath: /var/lib/postgresql/data
         - name: init
           mountPath: /docker-entrypoint-initdb.d
---