---
kind: Service
apiVersion: v1
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  type: NodePort
  selector:
    component: "ghost"
  ports:
    - port: 3001
      nodePort: 33901
      name: "web"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  serviceName: ghost
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
        component: ghost
    spec:
      containers:
        - name: ghost-container
          ports:
            - containerPort: 3001
              protocol: TCP
          # https://hub.docker.com/_/ghost
          image: ghost:3.5.0
          volumeMounts:
            - name: ghost-content
              mountPath: /var/lib/ghost/content
  volumeClaimTemplates:
    - metadata:
        name: ghost-content
        labels:
          app: ghost
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 128Mi
