---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  selector:
    component: ldap
  ports:
    - port: 389
      targetPort: 389
      name: ldap
    - port: 636
      targetPort: 636
      name: sslldap
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  serviceName: ldap
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
        component: ldap
    spec:
      containers:
        - name: ldap
          ports:
            - containerPort: 389
              protocol: TCP
            - containerPort: 636
              protocol: TCP
          image: osixia/openldap:1.3.0
          # https://github.com/osixia/docker-openldap
          env:
            - name: LDAP_ADMIN_PASSWORD
              value: "secret"
            - name: LDAP_ORGANISATION
              value: "My Company"
            - name: LDAP_DOMAIN
              value: "my-company.com"
            - name: LDAP_TLS
              value: "false"
          volumeMounts:
            - name: var-lib-ldap
              mountPath: /var/lib/postgresql/data"
            - name: etc-ldap-slapd-d
              mountPath: /var/lib/postgresql/data"
  volumeClaimTemplates:
    - metadata:
        name: var-lib-ldap
        labels:
          app: ldap
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
    - metadata:
        name: etc-ldap-slapd-d
        labels:
          app: ldap
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-admin
  labels:
    app: ldap
spec:
  type: NodePort
  selector:
    component: ldap-admin
  ports:
    - port: 80
      nodePort: 30300
      name: http
    - port: 443
      nodePort: 30301
      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-admin
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
        component: ldap-admin
    spec:
      containers:
        - name: ldap-admin
          image: osixia/phpldapadmin:0.9.0
          ports:
            - containerPort: 443
            - containerPort: 80
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "ldap"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
