---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers-json
  labels:
    app: pgadmin
data:
  servers.json: |
    {
      "Servers": {
          "1": {
              "Name": "Gerrit Review Database",
              "Group": "Servers",
              "Host": "gerrit-reviewdatabase",
              "Port": 5432,
              "MaintenanceDB": "reviewdb",
              "Username": "postgres",
              "SSLMode": "prefer",
              "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
              "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
              "SSLCompression": 0,
              "Timeout": 10,
              "UseSSHTunnel": 0,
              "TunnelPort": "22",
              "TunnelAuthentication": 0
          },
          "2": {
              "Name": "Sonarqube",
              "Group": "Servers",
              "Host": "sonarqube-database",
              "Port": 5432,
              "MaintenanceDB": "sonarqube",
              "Username": "postgres",
              "SSLMode": "prefer",
              "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
              "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
              "SSLCompression": 0,
              "Timeout": 10,
              "UseSSHTunnel": 0,
              "TunnelPort": "22",
              "TunnelAuthentication": 0
          }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AbG9jYWxob3N0
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4=
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  type: NodePort
  selector:
    component: pgadmin
  ports:
    - port: 80
      nodePort: 32204
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        component: pgadmin
    spec:
      volumes:
        - name: servers
          configMap:
            name: pgadmin-servers-json
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4:4.18
          ports:
            - containerPort: 80
          volumeMounts:
            - name: servers
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_PASSWORD
