---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  labels:
    app: sonarqube
data:
  postgresql_username: cG9zdGdyZXM=
  postgresql_password: QXNraXY0VmlSZkNVZGl3VA==
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-database
  labels:
    app: sonarqube
spec:
  type: NodePort
  selector:
    component: sonarqube-database
  ports:
  - port: 5432
    nodePort: 31701
    name: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube-database
  labels:
    app: sonarqube
spec:
  serviceName: sonarqube-database
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
        component: sonarqube-database
    spec:
      volumes:
        # FIXME: FIX-002 Add persistent volume over linux
        #  Postgres does not support windows volumes
        - name: data
          emptyDir:
            medium: Memory
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        env:
          - name: POSTGRES_DB
            value: "sonarqube"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: sonarqube-secret
                key: postgresql_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sonarqube-secret
                key: postgresql_password
        volumeMounts:
         - name: data
           mountPath: /var/lib/postgresql/data"
---
kind: Service
apiVersion: v1
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  type: NodePort
  selector:
    component: "sonarqube"
  ports:
    - port: 9000
      nodePort: 31700
      name: "web"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  serviceName: "sonarqube"
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
        component: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:8.1-community-beta
          resources:
            limits:
              memory: "2048Mi"
              cpu: "400m"
          env:
            - name: sonar.jdbc.url
              value: "jdbc:postgresql://sonarqube-database/sonarqube"
            - name: sonar.jdbc.username
              valueFrom:
                secretKeyRef:
                  name: sonarqube-secret
                  key: postgresql_username
            - name: sonar.jdbc.password
              valueFrom:
                secretKeyRef:
                  name: sonarqube-secret
                  key: postgresql_password
          volumeMounts:
            - name: sonarqube-conf
              mountPath: /opt/sonarqube/conf
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
  volumeClaimTemplates:
    - metadata:
        name: sonarqube-conf
        labels:
          app: sonarqube
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 128Mi
    - metadata:
        name: sonarqube-data
        labels:
          app: sonarqube
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: sonarqube-logs
        labels:
          app: sonarqube
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 128Mi
    - metadata:
        name: sonarqube-extensions
        labels:
          app: sonarqube
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 512Mi
