logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.client: DEBUG

microservice:
  uri: "http://localhost:1090"

mockserver:
  host: localhost
  port: 1090
