 pipeline {
        agent {
            kubernetes {
                defaultContainer 'jnlp'
                yamlFile 'agent.yaml'
            }
        }
        stages {
            stage('Jenkins: Perform in agents') {
                steps {
                    // container('busybox') {
                    //     sh "ls"
                    // }
                    container('docker') {
                        sh "docker ps"
                        sh "pwd"
                        sh "cd /workspace"
                        sh "./build.sh"
                    }
                }
            }
        }
        post {
            always {
                echo 'This will always run'
            }
            success {
                echo 'This will run only if successful'
            }
            failure {
                echo 'This will run only if failed'
            }
            unstable {
                echo 'This will run only if the run was marked as unstable'
            }
            changed {
                echo 'This will run only if the state of the Pipeline has changed'
                echo 'For example, if the Pipeline was previously failing but is now successful'
            }
        }
 }