{
 "title": "Batch With Stopwatch",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes, instance)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_classes_loaded_classes{instance=\"$instance\"}, application)"
   },
   {
    "name": "task_name",
    "label": "Task name",
    "query": "label_values(batch_with_stopwatch_total_task_seconds_max{instance=\"$instance\",application=\"$application\"}, task_name)"
   },
   {
    "name": "unique_id",
    "label": "Task UUID",
    "query": "label_values(batch_with_stopwatch_total_task_seconds_max{instance=\"$instance\",application=\"$application\",task_name=\"$task_name\"}, unique_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "batch_with_stopwatch_partition_size{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "Partition size"
    },
    {
     "expr": "batch_with_stopwatch_total_size{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "Collection size"
    },
    {
     "expr": "batch_with_stopwatch_current_element{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "Partition counter"
    },
    {
     "expr": "batch_with_stopwatch_total_size{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}-batch_with_stopwatch_current_element{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Start date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_with_stopwatch_start_timestamp{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "Start date"
    }
   ]
  },
  {
   "title": "Estimated end date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_with_stopwatch_end_timestamp{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "End date"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_with_stopwatch_total_size{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "batch_with_stopwatch_current_element{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "Current progress"
    }
   ]
  },
  {
   "title": "Elements per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Throughput" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1/batch_with_stopwatch_total_task_seconds_duration_sum{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}*batch_with_stopwatch_partition_size{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "Partition duration"
    }
   ]
  },
  { "title": "Batch With Stopwatch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Duration of partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "batch_with_stopwatch_total_task_seconds_duration_sum{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}",
     "legendFormat": "Partition duration"
    }
   ]
  },
  {
   "title": "Success/Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(batch_with_stopwatch_elements_consumed_total{application=\"$application\",instance=\"$instance\",task_name=\"$task_name\",unique_id=\"$unique_id\"}[$__interval])"
    }
   ]
  }
 ]
}