---
- name: Set DNS
  gather_facts: false
  hosts: all
  vars_prompt:
    - name: ip
      private: false
    - name: chown_user
      default: vagrant
      private: false
  tasks:
    - name: Create netplan configuration for DNS
      become: true
      copy:
        dest: "/etc/netplan/02-k8s-dns.yaml"
        content: |
          network:
            ethernets:
              eth0:
                nameservers:
                  adresses:
                    - "{{ ip }}"
    - name: Disable DNSSEC
      become: true
      blockinfile:
        create: true
        dest: /etc/systemd/resolved.conf.d/dnssec.conf
        block: |
          [Resolve]
          DNSSEC=false
        owner: "{{ chown_user }}"
      notify: Restart services

  handlers:
    - name: Restart services
      become: true
      service:
        name: systemd-resolved
        state: restarted
    - name: Apply configuration
      become: true
      command: netplan apply

# resolvectl status
# sudo systemctl status systemd-resolved.service