apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plantuml-namespace

commonLabels:
  ventheAppIdentifier: plantuml

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: plantuml-service
  path: plantuml-service-patch.yaml

images:
  - name: plantuml/plantuml-server
    newTag: jetty-v1.2020.17

resources:
  - manifests/namespace.yaml
  - manifests/plantuml.yaml
