apiVersion: v1
kind: Service
metadata:
  name: redmine-database-service
  labels:
    app: redmine
spec:
  selector:
    app: redmine
    component: redmine-database
  ports:
    - port: 5432
      name: pgsql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redmine-database-statefulset
  labels:
    app: redmine
spec:
  serviceName: redmine-database
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
        component: redmine-database
    spec:
      containers:
        # https://hub.docker.com/_/postgres
        - name: redmine-database
          image: postgres:13
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: redmine-secret
                  key: db_username
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: redmine-secret
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmine-secret
                  key: db_password
          volumeMounts:
            - name: redmine-database-data-persistentvolumeclaim
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: redmine-database-data-persistentvolumeclaim
        labels:
          app: redmine
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "512Mi"
