apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phpmyadmin-namespace

commonLabels:
  ventheAppIdentifier: phpmyadmin

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: phpmyadmin-service
  path: phpmyadmin-service-patch.yaml

images:
  - name: phpmyadmin/phpmyadmin
    newTag: "5.0.2"

resources:
  - manifests/namespace.yaml
  - manifests/phpmyadmin.yaml
