image:
  tag: 1.0.0-alpha.4
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: ca-issuer
  hosts:
    - host: mongo-express.home.arpa
      paths:
        - /
  tls:
    - secretName: mongo-express-tls
      hosts:
        - mongo-express.home.arpa
mongodbAdminPassword: rxrxiOB9jj
mongodbEnableAdmin: true
