apiVersion: v1
kind: Service
metadata:
  namespace: external-dns
  name: coredns-public
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  type: LoadBalancer
  ports:
   # - port: 53
   #   targetPort: 53
   #   protocol: TCP
   #   name: tcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: udp
  selector:
    app.kubernetes.io/name: coredns
