extraScrapeConfigs: |
  - job_name: grafana
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - grafana:80

server:
  strategy:
    type: "Recreate"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - "prometheus.{{ tld_hostname }}"
    tls:
      - hosts:
          - "prometheus.{{ tld_hostname }}"
        secretName: "prometheus-tls"