kind: Service
apiVersion: v1
metadata:
  name: redmine-service
  labels:
    app: redmine
spec:
  type: NodePort
  selector:
    component: redmine
  ports:
    - port: 3000
      nodePort: 31972
      name: "http"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redmine-statefulset
  labels:
    app: redmine
spec:
  serviceName: redmine-service
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
        component: redmine
    spec:
      containers:
        - name: redmine-container
          ports:
            - containerPort: 3000
              protocol: TCP
          # https://hub.docker.com/_/redmine
          image: redmine:4.1.1
          env:
            - name: REDMINE_DB_POSTGRES
              value: redmine-database-service
            - name: REDMINE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: redmine-secret
                  key: db_username
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmine-secret
                  key: db_password
