apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redmine-namespace

commonLabels:
  ventheAppIdentifier: redmine

secretGenerator:
  - name: redmine-secret
    type: Opaque
    env: secrets/database-secret.txt

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: redmine-service
  path: redmine-service-patch.yaml

images:
  - name: postgres
    newTag: "13"
  - name: redmine
    newTag: "4.1.1"

resources:
  - manifests/namespace.yaml
  - manifests/database.yaml
  - manifests/redmine.yaml
