---
- name: Install Helm
  gather_facts: false
  hosts: all
  tasks:
    - name: Add helm repository signing key
      become: true
      apt_key:
        url: https://baltocdn.com/helm/signing.asc
        # state: present
    - name: Add helm apt repository
      become: true
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        # state: present
        filename: helm
    - name: Install Helm
      become: true
      apt:
        name: "helm"
...
